aerospike_host = localhost
aerospike_port = 3000
aerospike_namespace = test
firefly_data_model = packed

edge_directory = firefly-spark-bulk-loader/src/main/resources/sampledata/edges
vertex_directory = firefly-spark-bulk-loader/src/main/resources/sampledata/vertices
use_provided_edge_id = false
keep_provided_edge_id_as_property = false
provided_edge_id_property_name = ~providedId
ignore_element_creation_failed = false
ignore_parse_failed_properties = true
sampling_percentage = 0.1
# Enable caching/persist of dataframe to avoid network transfer cost in AWS during shuffle operation.
# If persist is enabled, provide a spark conf `spark.local.dir` to spark-submit to allow custom scratch directory for Spark
enable_dataframe_caching = false
# persist options - memory/disk/memory_and_disk
dataframe_storage_type = disk
