aerospike_host = localhost
aerospike_port = 3000
aerospike_namespace = test
firefly_data_model = packed

drop_database = true
drop_indexes = false
edge_directory = /Users/mbelsare/Downloads/bulk-loader-input/edges
vertex_directory = /Users/mbelsare/Downloads/bulk-loader-input/vertices
id_buffer_count = 50
use_provided_id = false
provided_id_property_name = ~providedId
