aerospike_host = localhost
aerospike_port = 3000
aerospike_namespace = test
firefly_data_model = packed

edge_directory = firefly-spark-bulk-loader/src/main/resources/sampledata/edges
vertex_directory = firefly-spark-bulk-loader/src/main/resources/sampledata/vertexes
