aerospike_host = localhost
aerospike_port = 3000
aerospike_namespace = test
firefly_data_model = packed

drop_database = true
drop_indexes = false
edge_directory = firefly-bulk-loader/src/main/resources/sampledata/edges
vertex_directory = firefly-bulk-loader/src/main/resources/sampledata/vertices
id_buffer_count = 50
use_provided_id = false
provided_id_property_name = ~providedId
