gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike.graph.traversal=gmodern2
aerospike.graph.id=modern2
aerospike.graph.data.model=packed
aerospike.client.namespace=test
aerospike.graph.auto.preheat.enabled=true
