gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike.graph.traversal=g
aerospike.graph.id=0
aerospike.graph.data.model=packed
aerospike.client.namespace=test
aerospike.client.port=3000
aerospike.client.host=172.17.0.1
aerospike.graph.auto.preheat.enabled=true