gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike.client.host=localhost
aerospike.client.port=3000
aerospike.client.namespace=test
aerospike.graph.data.model=packed
aerospike.graph.http.port=9092
aerospike.graph.id=modern
