gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike.graph.usage.update.interval=123
aerospike.graph.traversal=gmodern
aerospike.graph.id=modern
aerospike.graph.data.model=packed
aerospike.client.namespace=test
aerospike.client.port=3000
aerospike.client.host=172.17.0.1
