aerospike.client.host=aerolab4-a customer-problem-9node-1
aerospike.client.port=3000
aerospike.client.namespace=test
aerospike.graphloader.edges=gs://a customer-test-synthetic/data/edges
aerospike.graphloader.vertices=gs://a customer-test-synthetic/data/vertices
aerospike.graphloader.temp-directory=gs://a customer-test-synthetic/temp