#FireflyGraph Configuration Defaults
#Wed Nov 16 01:05:11 MST 2022

#Aerospike cluster connection details
AEROSPIKE_HOST=localhost
AEROSPIKE_NAMESPACE=test
AEROSPIKE_PORT=3000

#Name of the graph
GRAPH_ID=0

ON_RECORD_ID_LIMIT=100000
EDGE_ID_BUFFER_SIZE=10000
VERTEX_ID_BUFFER_SIZE=1000
PROPERTY_ID_BUFFER_SIZE=10000
AEROSPIKE_CONNECTION_MAX_RETRY=10

ADJACENCY_INDEX_ENABLED=true


OPTIMIZED_TWO_HOP_STEPS=

#Strategies to enable
ENABLE_FAST_COUNT_STRATEGY=false
ENABLE_FIREFLY_DROP_STRATEGY=true
ENABLE_READ_THROUGH_CACHE=true
ENABLE_PREFETCH_STRATEGY=true

ASYNC_SUBGRAPH_CACHE=false


METADATA_UPDATE_FREQUENCY=3600000
SCAN_MAX_WAIT=2000

USER_SUPPLIED_ID_VERTEX_PROPERTY_CACHE=USER_SUPPLIED_ID_VERTEX_PROPERTY_CACHE

#Override the names of sets used by FireflyGraph
OUT_OUT_SET=OUT_OUT
IN_VP_SET=IN_VP
OUT_VP_SET=OUT_VP
OUT_IN_SET=OUT_IN
EDGE_AERO_SET=EDGE
USER_SUPPLIED_ID_CACHE_SET=USER_SUPPLIED_ID_CACHE_SET
ID_MANAGER_SET=ID_MGR_SET
VERTEX_PROPERTY_AERO_SET=V_PROP
TEST_SET=TEST_SET
GRAPH_METADATA_SET=G_META
GRAPH_VARIABLES_SET=G_VAR
IN_OUT_SET=IN_OUT
VERTEX_AERO_SET=VERTEX
VERTEX_EDGELIST_AERO_SET=E_LIST
IN_IN_SET=IN_IN
VERTEX_PROPERTY_SET=VP

#Override names of bins used by FireflyGraph
E_IN_INDEX=E_IN_INDEX
EDGE_LABEL_TO_EDGE_LABEL_TO_EDGES_BIN=E_L_E_L_E
USER_SUPPLIED_ID_VERTEX_CACHE=USER_SUPPLIED_ID_VERTEX_CACHE
USER_SUPPLIED_ID_EDGE_CACHE=USER_SUPPLIED_ID_EDGE_CACHE
PARENT_VERTEX_ID=PAR_V_ID
VERTEX_ID_KEY=V_ID_KEY
OUT_EDGES=OUT_EDGES
OPTIMIZED_HOP_CONSTRAINT_STEPS=
VERTEX_PROPERTY_NAME_TO_ID=VP_N_ID
IN_EDGE_COUNTER=IN_E_CTR
GRAPH_VARIABLES_RECORD=G_VAR_REC
CACHE_DISABLED=CACHE_DISABLED
VERTEX_PROPERTY_NAME_TO_VALUE=VP_N_V
RELATIONAL_VERTEX_TYPE_HINT=V_TYP_HNT
EDGE_PROPERTIES=E_PROP
E_LABEL_INDEX=E_LABEL_IDX
NUMERIC_VP_KV_INDEX=N_VP_KV
VERTEX_PROPERTY_ID_KEY=VP_ID_K
EDGE_ID_BIN=E_ID_BIN
VERTEX_ID_BIN=V_ID_BIN
COUNTER=COUNTER
INDEX_META=INDEX_META
ENABLE_PERIODIC_METADATA_UPDATE=false
VP_PROPERTIES=VP_PROP
GRAPH_VARIABLES_MAP=G_VAR_MAP
ID_TYPE=ID_TYPE
VERTEX_PROPERTY_ID_BIN=VP_P_ID_B
STRING_E_KV_INDEX=S_E_KV
NUMERIC_E_KV_INDEX=N_E_KV
VERTEX_PROPERTY_NAME=VP_NAME
EDGE_CACHE_DISABLED_GLOBALLY=false
VP_COUNTER=VP_COUNT
GLOBAL=GLOBAL
INDEXED_BINS=indexedBins
NUMERIC_V_VP_KV_INDEX=N_V_VP_KV
TYPE_HINTS=TYPE_HINTS
EDGE_ID_KEY=E_ID_KEY
OUT_EDGE_COUNTER=OUT_E_CTR
KEY_VALUE=KEY_VALUE
V_LABEL_INDEX=V_LABEL_IDX
VERTEX_PROPERTY_NAME_TO_VALUE_TYPE_HINT=VP_N_TH
IN_EDGES=IN_EDGES
STRING_VP_KV_INDEX=S_VP_KV
STRING_V_VP_KV_INDEX=S_V_VP_KV
E_OUT_INDEX=E_OUT_INDEX