#User exposed configurations

#Logging output level
log_level=INFO
aerospike_host=172.17.0.1
aerospike_port=3000
aerospike_namespace=test
vertex_property_indexes=a,b,c,d
edge_property_indexes=e,f,g,h
tls=false
v_label_index_enabled=false
e_label_index_enabled=false
adjacency_index_enabled=false


#Advanced configurations

#Data model implementation name
firefly_data_model=packed
#Set prefix
graph_id=0
scan_max_wait=2000
aerospike_timeout=2000
async_subgraph_cache=false
max_connections_per_node=2000
on_record_id_limit=100000
edge_cache_disabled_globally=false
enable_fast_count_strategy=true
enable_read_through_cache=true
enable_prefetch_strategy=true
enable_firefly_drop_strategy=true
enable_composite_id_strategy=true
enable_batch_edge_read_strategy=true
aerospike_connection_max_retry=10
vertex_id_buffer_size=1000
edge_id_buffer_size=10000
property_id_buffer_size=10000
cardinality_metadata_update_frequency=3600000
index_metadata_update_frequency=30000
optimized_two_hop_steps=
optimized_hop_constraint_steps=
aerospike_batch_read_size=5000
firefly_read_through_cache_weight=1000000
phat_edge_size=10



