#FireflyGraph Configuration Defaults
#Wed Nov 16 01:05:11 MST 2022

#Aerospike cluster connection details
aerospike_host=localhost
aerospike_namespace=test
aerospike_port=3000

#Name of the graph
graph_id=0

on_record_id_limit=100000
edge_id_buffer_size=10000
vertex_id_buffer_size=1000
property_id_buffer_size=10000
aerospike_connection_max_retry=10

adjacency_index_enabled=true


optimized_two_hop_steps=

#Strategies to enable
enable_fast_count_strategy=false
enable_firefly_drop_strategy=true
enable_read_through_cache=true
enable_prefetch_strategy=true

async_subgraph_cache=false


cardinality_metadata_update_frequency=3600000
scan_max_wait=2000

user_supplied_id_vertex_property_cache=user_supplied_id_vertex_property_cache

#Override the names of sets used by FireflyGraph
out_out_set=out_out
in_vp_set=in_vp
out_vp_set=out_vp
out_in_set=out_in
edge_aero_set=edge
user_supplied_id_cache_set=user_supplied_id_cache_set
id_manager_set=id_mgr_set
vertex_property_aero_set=v_prop
test_set=test_set
graph_metadata_set=g_meta
graph_variables_set=g_var
in_out_set=in_out
vertex_aero_set=vertex
in_in_set=in_in
vertex_property_set=vp

#Override names of bins used by FireflyGraph
e_in_index=e_in_index
edge_label_to_edge_label_to_edges_bin=e_l_e_l_e
user_supplied_id_vertex_cache=user_supplied_id_vertex_cache
user_supplied_id_edge_cache=user_supplied_id_edge_cache
parent_vertex_id=par_v_id
vertex_id_key=v_id_key
out_edges=out_edges
optimized_hop_constraint_steps=
vertex_property_name_to_id=vp_n_id
in_edge_counter=in_e_ctr
graph_variables_record=g_var_rec
cache_disabled=cache_disabled
vertex_property_name_to_value=vp_n_v
relational_vertex_type_hint=v_typ_hnt
properties=properties
e_label_index=e_label_idx
vertex_property_id_key=vp_id_k
edge_id_bin=e_id_bin
vertex_id_bin=v_id_bin
counter=counter
index_meta=index_meta
enable_periodic_metadata_update=false
vp_properties=vp_prop
graph_variables_map=g_var_map
id_type=id_type
vertex_property_id_bin=vp_p_id_b
vertex_property_name=vp_name
edge_cache_disabled_globally=false
global=global
indexed_bins=indexedbins
type_hints=type_hints
edge_id_key=e_id_key
out_edge_counter=out_e_ctr
v_label_index=v_label_idx
vertex_property_name_to_value_type_hint=vp_n_th
in_edges=in_edges
e_out_index=e_out_index
vertex_property_indexes=propertya,propertyb
edge_property_indexes=propertya,propertyb
