gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike_host=172.17.0.1
aerospike_port=3000
aerospike_namespace=test
firefly_data_model=packed
vertex_property_indexes=code
e_label_index_enabled = false
v_label_index_enabled = true
