aerospike_host = 172.17.0.1
aerospike_port = 3000
aerospike_namespace = test

firefly_data_model = packed
# This property file contains sindex for all the graphs used in test suite
vertex_property_indexes=name,lang,age,songType,performances,location

