FROM alpine:latest AS build

# Set input arguments.
ARG FIREFLY_GRAPH

# Set environment variables.
ENV CONF_DIR="/opt/conf"

RUN apk add --no-cache --update bash dos2unix

COPY ${FIREFLY_GRAPH} /opt/firefly-graph.jar
COPY conf/docker-default/flattened-default-gremlin-server.yaml $CONF_DIR/flattened-default-gremlin-server.yaml
COPY docker-runtime-scripts/gremlin-server-docker.sh /opt/scripts/gremlin-server-docker.sh
COPY docker-runtime-scripts/firefly-server.sh /opt/scripts/firefly-server.sh
COPY docker-runtime-scripts/graph_config/configure_aerospike_graph.py /opt/scripts/graph_config/configure_aerospike_graph.py
COPY conf/logback.xml $CONF_DIR/logback.xml
COPY .git .git

WORKDIR /opt

# For Windows users fix for line endings
RUN dos2unix /opt/scripts/gremlin-server-docker.sh /opt/scripts/firefly-server.sh && apk del dos2unix

FROM alpine:latest AS main

# Set environment variables.
ENV CONF_DIR="/opt/conf"
ENV OUTPUT_SERVER_YAML="$CONF_DIR/aerospike-graph-service.yaml"
ENV HEALTHCHECK_FILE="/tmp/firefly-ready"

COPY --from=build /opt /opt

RUN apk upgrade --no-cache && \
    apk add --no-cache bash openjdk17-jdk python3 py3-pip openssl
RUN pip install pyyaml --break-system-packages

WORKDIR /opt

# Make gremlin-server-docker.sh runnable and make files in config dir read/write/executable.
RUN chmod +x scripts/gremlin-server-docker.sh
RUN chmod +x scripts/firefly-server.sh
RUN chmod -R 777 $CONF_DIR

HEALTHCHECK CMD ls $HEALTHCHECK_FILE

ENTRYPOINT ["scripts/gremlin-server-docker.sh"]
