FROM alpine AS build

# Set input arguments.
ARG FIREFLY_GRAPH

# Set environment variables.
ENV CONF_DIR="/opt/conf"

RUN apk add --no-cache --update bash dos2unix openjdk11-jdk

COPY ${FIREFLY_GRAPH} /opt/firefly-graph.jar
COPY conf/docker-default/flattened-default-gremlin-server.yaml $CONF_DIR/flattened-default-gremlin-server.yaml
COPY docker-runtime-scripts /opt/scripts

WORKDIR /opt

# For Windows users fix for line endings
RUN dos2unix /opt/scripts/gremlin-server-docker.sh /opt/scripts/firefly-server.sh && apk del dos2unix

# Add firefly logback config to container.
COPY conf/logback.xml $CONF_DIR/logback.xml

FROM alpine AS main

# Set environment variables.
ENV CONF_DIR="/opt/conf"
ENV OUTPUT_SERVER_YAML="$CONF_DIR/aerospike-graph-service.yaml"

COPY --from=build /opt /opt

RUN apk add --no-cache --update \
    bash \
    python3

WORKDIR /opt

# Make gremlin-server-docker.sh runnable and make files in config dir read/write/executable.
RUN chmod +x scripts/gremlin-server-docker.sh
RUN chmod +x scripts/firefly-server.sh
RUN chmod -R 777 $CONF_DIR

HEALTHCHECK CMD ls /tmp/firefly-ready

ENTRYPOINT ["scripts/gremlin-server-docker.sh"]
