FROM eclipse-temurin:17-jre-alpine AS build

# Set input arguments.
ARG FIREFLY_GRAPH
ARG BULKLOADER

# Set environment variables.
ENV CONF_DIR="/opt/conf"

RUN apk add --no-cache --update bash

COPY ${FIREFLY_GRAPH} /opt/firefly-graph.jar
COPY ${BULKLOADER} /opt/bulk-loader.jar

# Add scripts to container.
COPY docker-runtime-scripts /opt/scripts

COPY conf/docker-default/flattened-default-gremlin-server.yaml $CONF_DIR/flattened-default-gremlin-server.yaml

# Add firefly logback config to container.
COPY conf/logback.xml $CONF_DIR/logback.xml

WORKDIR /opt

# Make gremlin-server-docker.sh runnable and make files in config dir read/write/executable.
RUN chmod +x scripts/gremlin-server-docker.sh
RUN chmod +x scripts/firefly-server.sh
RUN chmod -R 777 $CONF_DIR

# Add user firefly.
RUN addgroup -S firefly && adduser -S -s /bin/false -G firefly firefly
RUN chown firefly:firefly -R /opt


FROM eclipse-temurin:17-jre-alpine AS main

# Set environment variables.
ENV CONF_DIR="/opt/conf"
ENV OUTPUT_SERVER_YAML="$CONF_DIR/aerospike-graph-service.yaml"

COPY --from=build /opt /opt

RUN apk add --no-cache --update \
    bash \
    python3

WORKDIR /opt

HEALTHCHECK CMD ls /tmp/firefly-ready

ENTRYPOINT ["scripts/gremlin-server-docker.sh"]
