# Copyright 2022-2026 Aerospike, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike.client.host=172.17.0.1
aerospike.client.port=3000
aerospike.client.namespace=test
aerospike.graph.log.level=DEBUG
aerospike.client.password=MASKME
aerospike.graph-service.auth.jwt.secret=MASKME
aerospike.graph-service.auth.jwt.issuer=aerospike
aerospike.graph-service.ssl.enabled=true
aerospike.graph-service.ssl.sslEnabledProtocols=[TLSv1.2]
aerospike.graph-service.ssl.keyStore=/root/aerospike/keystore.jks
aerospike.graph-service.ssl.keyStorePassword=MASKMEKSP
aerospike.graph-service.ssl.trustStore=/root/aerospike/truststore.jks
aerospike.graph-service.ssl.trustStorePassword=MASKMETSP
