gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike.client.host=172.17.0.1
aerospike.client.port=3000
aerospike.client.namespace=test
aerospike.graph.log.level=DEBUG
aerospike.client.password=simon
aerospike.graph-service.auth.jwt.secret=simon
aerospike.graph-service.auth.jwt.issuer=aerospike
aerospike.graph-service.ssl={enabled: true, sslEnabledProtocols: [TLSv1.2], keyStore: /root/aerospike/keystore.jks, keyStorePassword: simonksp, trustStore: /root/aerospike/truststore.jks, trustStorePassword: simontsp }
