gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike.client.host=172.17.0.1
aerospike.client.port=3000
aerospike.client.namespace=test
aerospike.graph.log.level=DEBUG
aerospike.client.password=simon
aerospike.graph-service.auth.jwt.secret=simon
aerospike.graph-service.auth.jwt.issuer=aerospike
aerospike.graph-service.ssl.enabled=true
aerospike.graph-service.ssl.sslEnabledProtocols=[TLSv1.2]
aerospike.graph-service.ssl.keyStore=/root/aerospike/keystore.jks
aerospike.graph-service.ssl.keyStorePassword=simonksp
aerospike.graph-service.ssl.trustStore=/root/aerospike/truststore.jks
aerospike.graph-service.ssl.trustStorePassword=simontsp
