# Aerospike database configuration file
# This template sets up a single-node, single namespace developer environment.
#
# Alternatively, you can pass in your own configuration file.
# You can see more examples at
# https://github.com/aerospike/aerospike-server/tree/master/as/etc

# This stanza must come first.
service {
    feature-key-file /opt/aerospike/etc/features.conf
}

logging {
	# Log file must be an absolute path.
	file /dev/null {
		context any info
	}

	# Send log messages to stdout
	console {
		context any info
	}
}

network {
    tls aerospike.test.aerospike.dev {
      cert-file /opt/aerospike/etc/aerospike_server.crt
      key-file /opt/aerospike/etc/aerospike_server.key
      ca-file /opt/aerospike/etc/ca.crt
      protocols TLSv1.2
    }
	service {
		address any
		access-address 172.17.0.1
		alternate-access-address 127.0.0.1
		access-port 3000
		port 3000
        tls-address any
        tls-port 4303
        tls-authenticate-client false
        tls-name aerospike.test.aerospike.dev

		# Uncomment the following to set the `access-address` parameter to the
		# IP address of the Docker host. This will the allow the server to correctly
		# publish the address which applications and other nodes in the cluster to
		# use when addressing this node.
		# access-address <IPADDR>
	}

	heartbeat {
		# mesh is used for environments that do not support multicast
		mode mesh
		address 0.0.0.0
		port 3002
		interval 150
		timeout 10
	}

	fabric {
		# Intra-cluster communication port (migrates, replication, etc)
		# default to same address in 'service'
		address 0.0.0.0
		port 3001
	}

}

namespace test {
	default-ttl 30d # use 0 to never expire/evict.
	memory-size 3G
	nsup-period 120
	replication-factor 1
	storage-engine device {
		data-in-memory false # if true, in-memory, persisted to the filesystem
		file /opt/aerospike/data/test.dat
		filesize 4G
		read-page-cache true
	}
}

