package com.aerospike.firefly.bulkloader.util;

import com.aerospike.firefly.util.ConfigurationHelper;
import org.apache.commons.configuration2.Configuration;
import org.apache.commons.configuration2.ex.ConfigurationRuntimeException;

import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

public class BulkLoaderConfigHelper {
    // Directory containing the Edge CSV files.
    public static final String EDGE_DIRECTORY_KEY = "edge_directory";
    // Directory containing the Vertex CSV files.
    public static final String VERTEX_DIRECTORY_KEY = "vertex_directory";
    // Boolean value to determine whether to use provided ID values for Edges or to use ones automatically generated by Firefly.
    public static final String KEEP_PROVIDED_EDGE_ID_AS_PROPERTY = "keep_provided_edge_id_as_property";
    // The key of the property to store the provided IDs for Edges in.
    public static final String PROVIDED_EDGE_ID_PROPERTY_NAME = "provided_edge_id_property_name";
    // Boolean value to ignore failures creating a Vertex or Edge and continue the bulk load.
    public static final String IGNORE_ELEMENT_CREATION_FAILED = "ignore_element_creation_failed";
    // Boolean value to ignore failures parsing specific properties on Vertices and Edges, e.g. specifying "hello world" to be parsed as a numeric value.
    public static final String IGNORE_PARSE_FAILED_PROPERTIES = "ignore_parse_failed_properties";
    // Percentage of the provided Vertex and Edge data to sample to verify integrity of the bulk load after completion.
    public static final String SAMPLING_PERCENTAGE = "sampling_percentage";
    // Flag to enable/disable to caching of dataframe
    public static final String ENABLE_DATAFRAME_CACHING = "enable_dataframe_caching";
    // Storage type for Dataframe persist operation
    public static final String DATAFRAME_STORAGE_TYPE = "dataframe_storage_type";
    // String value of what should be parsed as a literal null value for properties. The null character \0 is a good alternative choice for this.
    public static final String NULL_VALUE = "null_value";

    private static final Map<String, String> DEFAULT_VALUES = new HashMap<>() {{
        put(KEEP_PROVIDED_EDGE_ID_AS_PROPERTY, "false");
        put(PROVIDED_EDGE_ID_PROPERTY_NAME, "~providedId");
        put(IGNORE_ELEMENT_CREATION_FAILED, "false");
        put(IGNORE_PARSE_FAILED_PROPERTIES, "true");
        put(SAMPLING_PERCENTAGE, "0.1");
        put(ENABLE_DATAFRAME_CACHING, "false");
        put(DATAFRAME_STORAGE_TYPE, "disk_only");
        put(NULL_VALUE, "null");
    }};

    private BulkLoaderConfigHelper() {

    }

    static public String getOrDefault(final String key, final Configuration config) {
        final String loweredKey = key.toLowerCase();
        if (config.containsKey(loweredKey)) {
            return config.get(String.class, loweredKey);
        } else if (DEFAULT_VALUES.containsKey(loweredKey)) {
            return DEFAULT_VALUES.get(loweredKey);
        } else {
            throw new ConfigurationRuntimeException("No default value available for key: " + loweredKey);
        }
    }

    static public Configuration getConfig(Path path) {
        return ConfigurationHelper.loadFromFile(path);
    }
}
