gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike.client.host=aerospike_host_to_replace
aerospike.client.port=aerospike_port_to_replace
aerospike.client.namespace=aerospike_namespace_to_replace
aerospike.graph.data.model=firefly_data_model_to_replace
