gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike_host=aerospike_host_to_replace
aerospike_port=aerospike_port_to_replace
aerospike_namespace=aerospike_namespace_to_replace
firefly_data_model=firefly_data_model_to_replace

