gremlin.graph=com.aerospike.firefly.structure.FireflyGraph
aerospike.graph-service.ssl={ enabled: true }
aerospike.client.host=localhost
aerospike.client.port=3000
aerospike.client.namespace=test
aerospike.graph.data.model=packed
aerospike.graph.usage.update.interval=100

# override
#graph.aerospike.graph.id=0
#graph.aerospike.graph.traversal=g

#modern.aerospike.graph.id=modern
#modern.aerospike.graph.traversal=gmodern
#modern.aerospike.graph.usage.update.interval=123

#aerospike.graph-service.graphs=graph,modern
aerospike.graph-service.graphs=1,2,a,A

