aerospike.client.namespace = test
aerospike.graph.data.model = packed
aerospike.graph.index.vertex.label.enabled=true
aerospike.graph.index.vertex.properties=macAddress

aerospike.graphloader.edges=gs://incremental-datasets/1g/edges
aerospike.graphloader.vertices=gs://incremental-datasets/1g/vertices
aerospike.graphloader.sampling-percentage = 1