aerospike.client.namespace=test

aerospike.graph.data.model=packed
aerospike.graph.index.vertex.label.enabled=true
aerospike.graph.index.vertex.properties=macAddress

aerospike.graphloader.sampling-percentage=1
