aerospike.client.host=aerolab4-synthetic-3-node-1
aerospike.client.port=3000
aerospike.client.namespace=test
aerospike.graph.index.vertex.label.enabled=true
aerospike.graphloader.edges=gs://incremental-datasets/synthetic/128g/edges
aerospike.graphloader.vertices=gs://incremental-datasets/synthetic/128g/vertices
aerospike.graphloader.temp-directory=gs://ishaan-scratch