name: Build OLAP and Test
permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      aerospike_conf:
        description: 'Aerospike configuration (<count>,<type>,<ssd count>,<version>)'
        required: true
        default: '8,n2d-highmem-16,4,7.0.*'
      spark_config:
        description: 'Spark configuration (<count>,<type>,<disk size>,<spark.executor.memoryOverhead>,<spark.executor.memory>,<spark.executor.cores>,<spark.task.cpus>,<olap.executor.cores - blank=vcpu*count>)'
        required: true
        default: '16,n2d-highmem-8,150,1024m,4g,1,1,'
      bulk_load_config:
        description: 'Bulk load configuration (<vertex files>,<edge files>,<scratch directory>,<properties>)'
        required: true
        default: 'gs://scale-free-graphs/PropertyCorrected/SF100M/vertices,gs://scale-free-graphs/PropertyCorrected/SF100M/edges,gs://olap-testing-scratch,aerospike.graph.index.vertex.label.enabled=true,aerospike.graph.phat.edge.size=10'
      benchmark_config:
        description: 'Benchmark configuration (<client instance>,<warmup count>,<execution count>)'
        required: true
        default: 'n2d-standard-4,1,2'
      olap_query:
        description: 'OLAP query to run (separated w/ "|")'
        required: true
        default: |
          'g.with("evaluationTimeout", 6000).withComputer().V().hasLabel("person").count()|g.with("evaluationTimeout", 6000).withComputer().V().hasLabel("person").out("knows").count()'
      cleanup_clusters:
        description: 'Cleanup clusters after the run - true/false - If true the Aerospike and Spark clusters will be destroyed after the run, otherwise they will be left running for debugging purposes.'
        required: true
        default: 'true'
env:
  features_b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
  features_file: ${{ github.workspace }}/.github/aerospike/features.conf
  custom_conf: ${{ github.workspace }}/.github/aerospike/aerospike-rf1.conf
  client_count: 1
  region: us-central1
  zone: us-central1-a
  project: firefly-aerospike

jobs:
  trigger-olap-benchmark:
    name: OLAP Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Clamp Runtime Variables from Grouped Inputs
        id: clamp
        run: |
          # Parse Aerospike configuration
          IFS=',' read -r AERO_COUNT AERO_TYPE AERO_SSD AERO_VER  <<< "${{ github.event.inputs.aerospike_conf }}"

          echo "aerospike_count=$AERO_COUNT" >> $GITHUB_ENV
          echo "aerospike_instance=$AERO_TYPE" >> $GITHUB_ENV
          echo "aerospike_ssd_count=$AERO_SSD" >> $GITHUB_ENV
          echo "aerospike_version=$AERO_VER" >> $GITHUB_ENV

          # Parse Spark configuration
          IFS=',' read -r SPARK_COUNT SPARK_TYPE SPARK_DISK SPARK_MEM_OV SPARK_MEM SPARK_CORES TASK_CPUS OLAP_EXEC <<< "${{ github.event.inputs.spark_config }}"

          echo "spark_node_count=$SPARK_COUNT" >> $GITHUB_ENV
          echo "spark_instance_type=$SPARK_TYPE" >> $GITHUB_ENV
          echo "spark_disk_size=$SPARK_DISK" >> $GITHUB_ENV
          echo "spark_executor_memory_overhead=$SPARK_MEM_OV" >> $GITHUB_ENV
          echo "spark_executor_memory=$SPARK_MEM" >> $GITHUB_ENV
          echo "spark_executor_cores=$SPARK_CORES" >> $GITHUB_ENV
          echo "spark_task_cpus=$TASK_CPUS" >> $GITHUB_ENV
          echo "olap_executor_cores=$OLAP_EXEC" >> $GITHUB_ENV

          # Parse bulk load config
          BULK_LOAD_INPUT="${{ github.event.inputs.bulk_load_config }}"
          BULK_VERTEX=$(echo "$BULK_LOAD_INPUT" | cut -d',' -f1)
          BULK_EDGE=$(echo "$BULK_LOAD_INPUT" | cut -d',' -f2)
          SCRATCH_DIR=$(echo "$BULK_LOAD_INPUT" | cut -d',' -f3)
          BULK_PROPS=$(echo "$BULK_LOAD_INPUT" | cut -d',' -f4-)

          echo "bulk_load_vertex_files=$BULK_VERTEX" >> $GITHUB_ENV
          echo "bulk_load_edge_files=$BULK_EDGE" >> $GITHUB_ENV
          echo "scratch_directory=$SCRATCH_DIR" >> $GITHUB_ENV

          IFS=';' read -ra kv_pairs <<< "$BULK_PROPS"
          BULK_PROPS_COMBINED=$(printf "%s|" "${kv_pairs[@]}")
          BULK_PROPS_COMBINED=${BULK_PROPS_COMBINED%|}  # trim trailing |
          echo "bulk_load_properties=$BULK_PROPS_COMBINED" >> $GITHUB_ENV

          # Parse benchmark config
          IFS=',' read -r CLIENT_INSTANCE WARMUP EXEC <<< "${{ github.event.inputs.benchmark_config }}"
          echo "client_instance_type=$CLIENT_INSTANCE" >> $GITHUB_ENV
          echo "olap_query_warmup_count=$WARMUP" >> $GITHUB_ENV
          echo "olap_query_execution_count=$EXEC" >> $GITHUB_ENV

          # OLAP query as-is
          echo "olap_query='${{ github.event.inputs.olap_query }}'" >> $GITHUB_ENV

          # Cleanup flag
          echo "cleanup_clusters=${{ github.event.inputs.cleanup_clusters }}" >> $GITHUB_ENV
          
          # Print the values for debugging
          echo "aerospike_count=${{ env.aerospike_count }}"
          echo "aerospike_instance=${{ env.aerospike_instance }}"
          echo "aerospike_version=${{ env.aerospike_version }}"
          echo "aerospike_ssd_count=${{ env.aerospike_ssd_count }}"
          echo "spark_node_count=${{ env.spark_node_count }}"
          echo "spark_instance_type=${{ env.spark_instance_type }}"
          echo "spark_disk_size=${{ env.spark_disk_size }}"
          echo "spark_executor_memory_overhead=${{ env.spark_executor_memory_overhead }}"
          echo "spark_executor_memory=${{ env.spark_executor_memory }}"
          echo "spark_executor_cores=${{ env.spark_executor_cores }}"
          echo "spark_task_cpus=${{ env.spark_task_cpus }}"
          echo "olap_executor_cores=${{ env.olap_executor_cores }}"
          echo "bulk_load_vertex_files=${{ env.bulk_load_vertex_files }}"
          echo "bulk_load_edge_files=${{ env.bulk_load_edge_files }}"
          echo "scratch_directory=${{ env.scratch_directory }}"
          echo "bulk_load_properties=${{ env.bulk_load_properties }}"
          echo "client_instance_type=${{ env.client_instance_type }}"
          echo "olap_query_warmup_count=${{ env.olap_query_warmup_count }}"
          echo "olap_query_execution_count=${{ env.olap_query_execution_count }}"
          echo "olap_query=${{ env.olap_query }}"
          echo "cleanup_clusters=${{ env.cleanup_clusters }}"