# Copyright 2022-2026 Aerospike, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build OLAP and Test
permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      aerospike_conf:
        description: 'Aerospike configuration (<count>,<type>,<ssd count>,<version>)'
        required: true
        default: '4,n2d-highmem-16,4,7.0.*'
      spark_config:
        description: 'Spark configuration (<count>,<type>,<disk size>,<spark.executor.memoryOverhead>,<spark.executor.memory>,<spark.executor.cores>,<spark.task.cpus>,<olap.executor.cores - blank=vcpu*count>)'
        required: true
        default: '32,n2d-highmem-8,150,1024m,4g,1,1,'
      bulk_load_config:
        description: 'Bulk load configuration (<vertex files>,<edge files>,<scratch directory>,<properties>)'
        required: true
        default: 'gs://scale-free-graphs/PropertyCorrected/SF100M/vertices,gs://scale-free-graphs/PropertyCorrected/SF100M/edges,gs://olap-testing-scratch,aerospike.graph.index.vertex.label.enabled=true,aerospike.graph.phat.edge.size=10'
      benchmark_config:
        description: 'Benchmark configuration (<client instance>,<warmup count>,<execution count>)'
        required: true
        default: 'n2d-standard-4,1,2'
      olap_query:
        description: 'OLAP query to run (separated w/ "|")'
        required: true
        default: 'g.with(\"evaluationTimeout\", 60000).withComputer().V().count()|g.with(\"evaluationTimeout\", 60000).withComputer().V().hasLabel(\"person\").out(\"knows\").count()'
      cleanup_clusters:
        description: 'Cleanup clusters after the run - true/false - If true the Aerospike and Spark clusters will be destroyed after the run, otherwise they will be left running for debugging purposes.'
        required: true
        default: 'true'
env:
  features_b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
  features_file: ${{ github.workspace }}/.github/aerospike/features.conf
  custom_conf: ${{ github.workspace }}/.github/aerospike/aerospike-rf1.conf
  client_count: 1
  region: us-central1
  zone: us-central1-a
  project: firefly-aerospike

jobs:
  trigger-olap-benchmark:
    name: OLAP Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Clamp Runtime Variables from Grouped Inputs
        id: clamp
        run: |
          # Parse Aerospike configuration
          IFS=',' read -r AERO_COUNT AERO_TYPE AERO_SSD AERO_VER  <<< "${{ github.event.inputs.aerospike_conf }}"

          echo "aerospike_count=$AERO_COUNT" >> $GITHUB_ENV
          echo "aerospike_instance=$AERO_TYPE" >> $GITHUB_ENV
          echo "aerospike_ssd_count=$AERO_SSD" >> $GITHUB_ENV
          echo "aerospike_version=$AERO_VER" >> $GITHUB_ENV

          # Parse Spark configuration
          IFS=',' read -r SPARK_COUNT SPARK_TYPE SPARK_DISK SPARK_MEM_OV SPARK_MEM SPARK_CORES TASK_CPUS OLAP_EXEC <<< "${{ github.event.inputs.spark_config }}"

          echo "spark_node_count=$SPARK_COUNT" >> $GITHUB_ENV
          echo "spark_instance_type=$SPARK_TYPE" >> $GITHUB_ENV
          echo "spark_disk_size=$SPARK_DISK" >> $GITHUB_ENV
          echo "spark_executor_memory_overhead=$SPARK_MEM_OV" >> $GITHUB_ENV
          echo "spark_executor_memory=$SPARK_MEM" >> $GITHUB_ENV
          echo "spark_executor_cores=$SPARK_CORES" >> $GITHUB_ENV
          echo "spark_task_cpus=$TASK_CPUS" >> $GITHUB_ENV
          echo "olap_executor_cores=$OLAP_EXEC" >> $GITHUB_ENV

          # Parse bulk load config
          BULK_LOAD_INPUT="${{ github.event.inputs.bulk_load_config }}"
          BULK_VERTEX=$(echo "$BULK_LOAD_INPUT" | cut -d',' -f1)
          BULK_EDGE=$(echo "$BULK_LOAD_INPUT" | cut -d',' -f2)
          SCRATCH_DIR=$(echo "$BULK_LOAD_INPUT" | cut -d',' -f3)
          BULK_PROPS=$(echo "$BULK_LOAD_INPUT" | cut -d',' -f4-)

          echo "bulk_load_vertex_files=$BULK_VERTEX" >> $GITHUB_ENV
          echo "bulk_load_edge_files=$BULK_EDGE" >> $GITHUB_ENV
          echo "scratch_directory=$SCRATCH_DIR" >> $GITHUB_ENV

          IFS=';' read -ra kv_pairs <<< "$BULK_PROPS"
          BULK_PROPS_COMBINED=$(printf "%s|" "${kv_pairs[@]}")
          BULK_PROPS_COMBINED=${BULK_PROPS_COMBINED%|}  # trim trailing |
          echo "bulk_load_properties=$BULK_PROPS_COMBINED" >> $GITHUB_ENV

          # Parse benchmark config
          IFS=',' read -r CLIENT_INSTANCE WARMUP EXEC <<< "${{ github.event.inputs.benchmark_config }}"
          echo "client_instance_type=$CLIENT_INSTANCE" >> $GITHUB_ENV
          echo "olap_query_warmup_count=$WARMUP" >> $GITHUB_ENV
          echo "olap_query_execution_count=$EXEC" >> $GITHUB_ENV

          # OLAP query as-is
          echo "olap_query_b64=$(echo "${{ github.event.inputs.olap_query }}" | base64 -w 0)" >> $GITHUB_ENV

          # Cleanup flag
          echo "cleanup_clusters=${{ github.event.inputs.cleanup_clusters }}" >> $GITHUB_ENV
      - name: Log environment
        run: |
          # Print the values for debugging
          echo "aerospike_count=${{ env.aerospike_count }}"
          echo "aerospike_instance=${{ env.aerospike_instance }}"
          echo "aerospike_version=${{ env.aerospike_version }}"
          echo "aerospike_ssd_count=${{ env.aerospike_ssd_count }}"
          echo "spark_node_count=${{ env.spark_node_count }}"
          echo "spark_instance_type=${{ env.spark_instance_type }}"
          echo "spark_disk_size=${{ env.spark_disk_size }}"
          echo "spark_executor_memory_overhead=${{ env.spark_executor_memory_overhead }}"
          echo "spark_executor_memory=${{ env.spark_executor_memory }}"
          echo "spark_executor_cores=${{ env.spark_executor_cores }}"
          echo "spark_task_cpus=${{ env.spark_task_cpus }}"
          echo "olap_executor_cores=${{ env.olap_executor_cores }}"
          echo "bulk_load_vertex_files=${{ env.bulk_load_vertex_files }}"
          echo "bulk_load_edge_files=${{ env.bulk_load_edge_files }}"
          echo "scratch_directory=${{ env.scratch_directory }}"
          echo "bulk_load_properties=${{ env.bulk_load_properties }}"
          echo "client_instance_type=${{ env.client_instance_type }}"
          echo "olap_query_warmup_count=${{ env.olap_query_warmup_count }}"
          echo "olap_query_execution_count=${{ env.olap_query_execution_count }}"
          echo "olap_query_b64=${{ env.olap_query_b64 }}"
          echo "cleanup_clusters=${{ env.cleanup_clusters }}"

      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Authorize gcloud CLI
        uses: step-security/google-github-auth@775fc4c80760272ef389c9f9f8d98de7db0c170d # v3.0.2
        with:
          credentials_json: ${{ secrets.GCS_KEYFILE_B64 }}

      - name: Download, Install, and Configure Aerolab
        run: |
          cd /tmp && wget https://github.com/aerospike/aerolab/releases/download/7.3.0/aerolab-linux-amd64-7.3.0.zip
          unzip aerolab-linux-amd64-7.3.0.zip -d /usr/local/bin/
          aerolab config backend -t gcp -o firefly-aerospike

      - name: Set Up gcloud CLI
        uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b # v1.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: step-security/setup-maven@8b5f727904660c4b112d02624218c791126af325 # v5.0.0
        with:
          maven-version: 3.9.5

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: step-security/setup-buildx-action@f931205d68723ad9589fd2a7e2ece238bf9de341 # v4.0.0

      - name: Latch Date and Time
        uses: Kaven-Universe/github-action-current-date-time@f2c12d90cff9c3e7b1f50430886e632fe31fcee1 # v1.4.0
        id: date_format
        with:
          format: "yyyy-MM-dd"

      - name: Clamp Runtime Variables to Environment
        run: |
          description_val=${{ steps.date_format.outputs.year }}${{ steps.date_format.outputs.month }}${{ steps.date_format.outputs.day }}${{ steps.date_format.outputs.seconds }}
          bulk_jar_uri_val=${{ env.scratch_directory }}/${description_val}/aerospike-graph-bulk-loader.jar
          olap_jar_uri_val=${{ env.scratch_directory }}/${description_val}/aerospike-graph-olap.jar
          properties_file_uri_val=gs://gha-ci-firefly-bulkloader/weekly-benchmark/${description_val}-perf/ags-properties.conf
          aerospike_name_val=aga-${description_val}-as
          dataproc_name_val=aga-${description_val}-dproc
          benchmark_client_name_val=aga-${description_val}-lg
          
          # Extract number of cores from instance type
          num_cores_per_instance=$(echo "${{ env.spark_instance_type }}" | grep -o '[0-9]\+$')
          if [ -z "${{ env.olap_executor_cores }}" ]; then
              spark_executor_cores_val=$((${{ env.spark_node_count }} * ${num_cores_per_instance}))
          else
              spark_executor_cores_val=${{ env.olap_executor_cores }}
          fi
          
          echo "description=${description_val}" >> $GITHUB_ENV
          echo "bulk_jar_uri=${bulk_jar_uri_val}" >> $GITHUB_ENV
          echo "olap_jar_uri=${olap_jar_uri_val}" >> $GITHUB_ENV
          echo "properties_file_uri=${properties_file_uri_val}" >> $GITHUB_ENV
          echo "aerospike_name=${aerospike_name_val}" >> $GITHUB_ENV
          echo "dataproc_name=${dataproc_name_val}" >> $GITHUB_ENV
          echo "benchmark_client_name=${benchmark_client_name_val}" >> $GITHUB_ENV
          echo "spark_executor_cores=${spark_executor_cores_val}" >> $GITHUB_ENV
          
          # Print the values for debugging
          echo "description=${{ env.description }}"
          echo "bulk_jar_uri=${{ env.bulk_jar_uri }}"
          echo "olap_jar_uri=${{ env.olap_jar_uri }}"
          echo "properties_file_uri=${{ env.properties_file_uri }}"
          echo "aerospike_name=${{ env.aerospike_name }}"
          echo "dataproc_name=${{ env.dataproc_name }}"
          echo "benchmark_client_name=${{ env.benchmark_client_name }}"
          echo "spark_executor_cores=${{ env.spark_executor_cores }}"
          

      - name: Build and publish Bulk Loader and OLAP artifacts
        run: |
          # Build bulk loader & OLAP artifacts.
          mvn clean install -DskipTests --no-transfer-progress
          
          # Copy the OLAP artifact to GCS.
          gcloud storage cp \
              ${{ github.workspace }}/aerospike-graph-olap/target/aerospike-graph-olap-*.jar \
              ${{ env.olap_jar_uri }}
          
          # Copy the bulk loader artifact to GCS.
          gcloud storage cp \
              ${{ github.workspace }}/aerospike-graph-bulk-loader/target/aerospike-graph-bulk-loader-*.jar \
              ${{ env.bulk_jar_uri }}

          # TODO: Generate and upload properties file.
          echo "aerospike.graphloader.vertices=${{ env.bulk_load_vertex_files }}" > ${{ github.workspace }}/benchmark-bulk-load-config.properties
          echo "aerospike.graphloader.edges=${{ env.bulk_load_edge_files }}" >> ${{ github.workspace }}/benchmark-bulk-load-config.properties
          echo "aerospike.graphloader.temp-directory=${{ env.scratch_directory }}/temp" >> ${{ github.workspace }}/benchmark-bulk-load-config.properties
          echo "aerospike.client.host=aerolab4-${{ env.aerospike_name }}-1" >> ${{ github.workspace }}/benchmark-bulk-load-config.properties
          # Loop through bulk_load_properties and split by '|'
          IFS='|' read -ra properties <<< "${{ env.bulk_load_properties }}"
          for property in "${properties[@]}"; do
              echo "$property" >> ${{ github.workspace }}/benchmark-bulk-load-config.properties
          done
          
          # Upload the properties file to GCS.
          gcloud storage cp \
                ${{ github.workspace }}/benchmark-bulk-load-config.properties \
                ${{ env.properties_file_uri }}

      - name: Deploy to GCP and Bulk Load
        run: |
          # Create Aerospike cluster.
          echo ${{ env.features_b64 }} | base64 -d > ${{ env.features_file }}
      
          aerolab cluster create \
            --zone ${{ env.zone }} \
            --name "${{ env.aerospike_name }}" \
            --count "${{ env.aerospike_count }}" \
            --instance "${{ env.aerospike_instance }}" \
            --aerospike-version "${{ env.aerospike_version }}" \
            --featurefile "${{ env.features_file }}" \
            --customconf "${{ env.custom_conf }}" \
            --disk pd-ssd:20 \
            --disk local-ssd@"${{ env.aerospike_ssd_count }}" \
            --start n
          
          # Partition cluster disks.
          aerolab cluster partition create \
            --name "${{ env.aerospike_name }}" \
            --filter-type nvme \
            --partitions 24,24,24,24
          
          aerolab cluster partition conf \
            --name "${{ env.aerospike_name }}" \
            --namespace test \
            --filter-type nvme \
            --filter-partitions 1,2,3,4 \
            --configure device
          
          # Start cluster.
          aerolab aerospike start --name="${{ env.aerospike_name }}"
          
          aerolab cluster list -j | jq '.' > ${{ github.workspace }}/clusters.json
          python3 ${{ github.workspace }}/scripts/generate_bulk_load_config.py ${{ env.aerospike_name }} ${{ github.workspace }}/benchmark-bulk-load-config.properties
          gcloud storage cp \
            ${{ github.workspace }}/benchmark-bulk-load-config.properties \
            ${{ env.properties_file_uri }}

          # Execute the dataproc command
          gcloud dataproc clusters create "${{ env.dataproc_name }}" \
            --enable-component-gateway \
            --region ${{ env.region }} \
            --zone ${{ env.zone }} \
            --master-machine-type "${{ env.spark_instance_type }}" \
            --master-boot-disk-type pd-ssd \
            --master-boot-disk-size ${{ env.spark_disk_size }} \
            --num-workers "${{ env.spark_node_count }}" \
            --worker-machine-type "${{ env.spark_instance_type }}" \
            --worker-boot-disk-type pd-ssd \
            --worker-boot-disk-size ${{ env.spark_disk_size }} \
            --image-version 2.2-debian12 \
            --properties spark:spark.history.fs.gs.outputstream.type=FLUSHABLE_COMPOSITE \
            --project ${{ env.project }}

          gcloud dataproc jobs submit spark \
            --class=com.aerospike.firefly.bulkloader.SparkBulkLoader \
            --jars="${{ env.bulk_jar_uri }}" \
            --cluster="${{ env.dataproc_name }}" \
            --region="${{ env.region }}" \
            -- -c "${{ env.properties_file_uri }}"

      - name: Launch Aerospike Graph Analytics
        run: |
          gcloud dataproc jobs submit spark \
              --class=com.aerospike.firefly.olap.DistributedGraphComputerMain \
              --jars="${{ env.olap_jar_uri }}" \
              --cluster="${{ env.dataproc_name }}" \
              --region="${{ env.region }}" \
              --async \
              --properties=\
              --properties=spark.executor.memoryOverhead=${{ env.spark_executor_memory_overhead }},\
          spark.executor.memory=${{ env.spark_executor_memory }},\
          spark.executor.cores=${{ env.spark_task_cpus }},\
          spark.task.cpus=${{ env.spark_task_cpus }},\
          spark.speculation=false,\
          spark.executor.instances=${{ env.spark_executor_cores }},\
          spark.dynamicAllocation.enabled=true,\
          spark.dynamicAllocation.minExecutors=${{ env.spark_executor_cores }},\
          spark.dynamicAllocation.maxExecutors=${{ env.spark_executor_cores }},\
          spark.dynamicAllocation.initialExecutors=${{ env.spark_executor_cores }},\
          spark.scheduler.minRegisteredResourcesRatio=1.0 \
              -- -c "${{ env.properties_file_uri }}"
          
          master_ip_address_val=$(gcloud compute instances list \
              --filter="name~'^${{ env.dataproc_name }}-m'" \
              --format="value(networkInterfaces[0].networkIP)")
          echo "master_ip_address=${master_ip_address_val}" >> $GITHUB_ENV

      - name: Run Benchmark
        run: |
          # Create client machine.
          aerolab client create none --zone=${{ env.zone }} --disk=pd-ssd:40 --instance ${{ env.client_instance_type }} -n ${{ env.benchmark_client_name }}
          aerolab client list -j | jq '.' > ${{ github.workspace }}/clients.json
          gcloud compute scp --zone=${{ env.zone }} ${{ github.workspace }}/scripts/run-benchmark-gcp-olap-benchmark.sh aerolab4-${{ env.benchmark_client_name }}-1:run-benchmark-gcp-olap-benchmark.sh
          gcloud compute ssh --zone=${{ env.zone }} aerolab4-${{ env.benchmark_client_name }}-1 --command "sudo bash run-benchmark-gcp-olap-benchmark.sh ${{ env.master_ip_address }} ${{ env.olap_query_b64}} ${{ env.olap_query_execution_count }} ${{ env.olap_query_warmup_count }}"

      - name: Retrieve Tinkerbench Results
        run: |
          tinkerbench_result_dir=$(gcloud compute ssh --zone=${{ env.zone }} aerolab4-${{ env.benchmark_client_name }}-1 --command "pwd")
          gcloud compute scp --zone=${{ env.zone }} aerolab4-${{ env.benchmark_client_name }}-1:${tinkerbench_result_dir}/tinkerbench/benchmark-result-* tinkerbench_output.json
          pwd
          ls -l
          cat tinkerbench_output.json

      - name: Publish Benchmark Results
        uses: benchmark-action/github-action-benchmark@4bdcce38c94cec68da58d012ac24b7b1155efe8b # v1.20.7
        with:
          name: Publish Benchmark Results
          tool: 'customSmallerIsBetter'
          output-file-path: tinkerbench_output.json
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
          fail-on-alert: false
          max-items-in-chart: 750
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: docs/

      - name: Stop dataproc cluster
        if: ${{ always() && env.cleanup_clusters == 'true' }}
        run: |
          echo "Deleting cluster: ${{ env.dataproc_name }}"
          gcloud dataproc clusters delete -q --region=${{ env.region }} ${{ env.dataproc_name }}

      - name: Stop Benchmark machine
        if: ${{ always() && env.cleanup_clusters == 'true' }}
        run: |
          yes | aerolab client destroy -n "${{ env.benchmark_client_name }}"

      - name: Stop Aerospike cluster
        if: ${{ always() && env.cleanup_clusters == 'true' }}
        run: |
          yes | aerolab cluster destroy -n "${{ env.aerospike_name }}"
