name: Build and Test Firefly

on:
  push:
    branches: [main,test-ready]
  pull_request:
    branches: [main,test-ready]

# Firefly has the following jobs:
# - Build Firefly Maven
# - Build Firefly Docker
# - Test Spark Bulk Loader
# - Test Linked Data Model
# - Test Packed Data Model
# - Test Star Packed Data Model

jobs:
  start-runner-build:
    name: Start Build Runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-09d4741104f30e958
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  build-firefly-maven:
    name: Build Firefly Maven
    needs: start-runner-build
    timeout-minutes: 120
    runs-on: ${{ needs.start-runner-build.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Maven Project
        run: |
          mvn clean package -DskipTests --no-transfer-progress
  stop-runner-build:
    name: Stop Build Runner
    needs:
      - build-firefly-maven
      - start-runner-build
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-build.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-build.outputs.ec2-instance-id }}
  start-runner-linked:
    name: Start Linked Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-09d4741104f30e958
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-movielens-linked:
    name: Start Movielens Linked Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-09d4741104f30e958
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-packed:
    name: Start Packed Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-09d4741104f30e958
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-movielens-packed:
    name: Start Movielens Packed Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-09d4741104f30e958
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-docker:
    name: Start Docker Build Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-09d4741104f30e958
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-spark-bulk-loader:
    name: Start Spark Bulk Loader Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-09d4741104f30e958
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  build-firefly-docker:
    name: Build Firefly Docker
    timeout-minutes: 120
    needs: start-runner-docker
    runs-on: ${{ needs.start-runner-docker.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          java -XX:+PrintFlagsFinal -version | grep HeapSize
          docker build -t aerospike/firefly .
  test-firefly-linked:
    name: Test Linked
    timeout-minutes: 120
    needs: start-runner-linked
    runs-on: ${{ needs.start-runner-linked.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v3
        with:
          server-version: 6.1.0.3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          mvn -pl firefly-gremlin -Dintegration.test.properties=linked test --no-transfer-progress
  test-firefly-movielens-linked:
    name: Test Movielens Linked
    timeout-minutes: 120
    needs: start-runner-movielens-linked
    runs-on: ${{ needs.start-runner-movielens-linked.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v3
        with:
          server-version: 6.1.0.3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          mvn test -pl firefly-gremlin -Dtest=TestMovielens1M -DfailIfNoTests=false -Dintegration.test.properties=linked --no-transfer-progress
  test-firefly-packed:
    name: Test Packed
    timeout-minutes: 120
    needs: start-runner-packed
    runs-on: ${{ needs.start-runner-packed.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v3
        with:
          server-version: 6.1.0.3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          mvn -pl firefly-gremlin -Dintegration.test.properties=packed test --no-transfer-progress
  test-firefly-movielens-packed:
    name: Test Movielens Packed
    timeout-minutes: 120
    needs: start-runner-movielens-packed
    runs-on: ${{ needs.start-runner-movielens-packed.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v3
        with:
          server-version: 6.1.0.3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          mvn test -pl firefly-gremlin -Dtest=TestMovielens1M -DfailIfNoTests=false -Dintegration.test.properties=packed --no-transfer-progress
  test-firefly-spark-bulk-loader:
    name: Test Spark Bulk Loader
    timeout-minutes: 15
    needs: start-runner-spark-bulk-loader
    runs-on: ${{ needs.start-runner-spark-bulk-loader.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v3
        with:
          server-version: 6.1.0.3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          mvn clean install -DskipTests
          mvn -pl firefly-spark-bulk-loader test --no-transfer-progress
  benchmark-firefly:
    name: Benchmark Firefly
    timeout-minutes: 240
    needs: build-firefly-maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v3
        with:
          server-version: 6.1.0.3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Launch Firefly in Gremlin-Server and Run Benchmark
        run: |
          echo "Downloading gremlin-server"
          cd ..
          wget -O gremlin-server https://dlcdn.apache.org/tinkerpop/3.6.0/apache-tinkerpop-gremlin-server-3.6.0-bin.zip --quiet
          echo "Unzipping gremlin-server"
          unzip -qq gremlin-server
  
          echo "Build Firefly"
          cd firefly
          mvn clean install -DskipTests --no-transfer-progress
  
          echo "Installing Firefly in gremlin-server"
          ../apache-tinkerpop-gremlin-server-3.6.0/bin/gremlin-server.sh install 'com.aerospike firefly-gremlin 0.3.0-SNAPSHOT'
  
          echo "Starting gremlin-server"
          ../apache-tinkerpop-gremlin-server-3.6.0/bin/gremlin-server.sh /home/runner/work/firefly/firefly/conf/firefly-gremlin-server-github-actions.yaml &
  
          echo "Sleeping for 30 seconds while gremlin-server starts"
          sleep 30
  
          echo "Running benchmark"
          mvn test -pl firefly-gremlin -Dtest=BenchmarkTest -DfailIfNoTests=false --no-transfer-progress
      - name: Publish Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Publish Benchmark Results
          tool: 'customSmallerIsBetter'
          output-file-path: firefly-gremlin/target/jmh-result.json
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: '@lyndonbauto @cinterloper @DKZed'
          github-token: ${{ secrets.PUBLISH_BENCHMARKS_TOKEN }}
          benchmark-data-dir-path: docs/
  stop-runner-linked:
    name: Stop Linked Runner
    needs:
      - test-firefly-linked
      - start-runner-linked
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-linked.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-linked.outputs.ec2-instance-id }}
  stop-runner-movielens-linked:
    name: Stop Movielens Linked Runner
    needs:
      - test-firefly-movielens-linked
      - start-runner-movielens-linked
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-movielens-linked.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-movielens-linked.outputs.ec2-instance-id }}
  stop-runner-movielens-packed:
    name: Stop Movielens Packed Runner
    needs:
      - test-firefly-movielens-packed
      - start-runner-movielens-packed
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-movielens-packed.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-movielens-packed.outputs.ec2-instance-id }}
  stop-runner-packed:
    name: Stop Packed Runner
    needs:
      - test-firefly-packed
      - start-runner-packed
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-packed.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-packed.outputs.ec2-instance-id }}
  stop-runner-docker:
    name: Stop Docker Build Runner
    needs:
      - build-firefly-docker
      - start-runner-docker
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-docker.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-docker.outputs.ec2-instance-id }}
  stop-runner-spark-bulk-loader:
    name: Stop Spark Bulk Loader Runner
    needs:
      - test-firefly-spark-bulk-loader
      - start-runner-spark-bulk-loader
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-spark-bulk-loader.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-spark-bulk-loader.outputs.ec2-instance-id }}
