name: Build and Test Firefly

on:
  push:
    branches: [main,1.x-dev]
  pull_request:
    branches: [main,1.x-dev]

# Firefly has the following jobs:
# - Build Firefly Maven
# - Build Firefly Docker
# - Test Spark Bulk Loader
# - Test Packed Data Model

jobs:
  start-runner-build:
    name: Start Build Runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  build-firefly-maven:
    name: Build Firefly Maven
    needs: start-runner-build
    timeout-minutes: 120
    runs-on: ${{ needs.start-runner-build.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Maven Project
        run: |
          # Run simple check to see if code is formatted properly before building.
          # If code is incorrectly formatted, it can be fixed automatically with:
          # mvn editorconfig:format
          mvn editorconfig:check
          mvn clean package -DskipTests --no-transfer-progress
  stop-runner-build:
    name: Stop Build Runner
    needs:
      - build-firefly-maven
      - start-runner-build
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-build.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-build.outputs.ec2-instance-id }}
  start-runner-tls:
    name: Start TLS Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-client-provider:
    name: Start Client Provider Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-packed-lz4:
    name: Start Packed Runner lz4
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-packed:
    name: Start Packed Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-packed-sindex:
    name: Start Packed Sindex Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-movielens-packed:
    name: Start Movielens Packed Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-small-memory-packed:
    name: Start Small Memory Packed Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-aerospike-version-minimum:
    name: Start Aerospike Minimum Version Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-invalid-feature-key:
    name: Start Invalid Feature Key
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-docker:
    name: Start Docker Build Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-benchmark:
    name: Start Benchmark Build Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-benchmark-internal dataset:
    name: Start Benchmark internal dataset Build Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-benchmark-identifies:
    name: Start Benchmark Identifies Build Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-spark-bulk-loader-lz4:
    name: Start Spark Bulk Loader Runner lz4
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  start-runner-spark-bulk-loader:
    name: Start Spark Bulk Loader Runner
    runs-on: ubuntu-latest
    needs: build-firefly-maven
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  build-firefly-docker:
    name: Build Firefly Docker
    timeout-minutes: 120
    needs: start-runner-docker
    runs-on: ${{ needs.start-runner-docker.outputs.label }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          java -XX:+PrintFlagsFinal -version | grep HeapSize
          bash -x scripts/build-docker.sh aerospike/firefly linux/amd64
  test-bulk-loader-call-docker:
    name: Bulk Loader Call with Spark
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCS_PRIVATE_KEY: ${{ secrets.GCS_PRIVATE_KEY }}
          GCS_PRIVATE_KEY_ID: ${{ secrets.GCS_PRIVATE_KEY_ID }}
          GCS_CLIENT_EMAIL: ${{ secrets.GCS_CLIENT_EMAIL }}
        run: |
          bash -x scripts/build-docker.sh aerospike/firefly-bulk-load linux/amd64
          
          docker run -p 8182:8182  \
            -v /home/runner/work/firefly/firefly/conf/docker-bulk-load/:/opt/aerospike-firefly/conf/ \
            -v /home/runner/work/firefly/firefly/data/docker-bulk-load/:/opt/aerospike-firefly/etc/ \
            aerospike/firefly-bulk-load &
          
          echo "Sleeping for 30 seconds while docker image starts"
          sleep 30
          
          mvn test -pl aerospike-graph-gremlin -Dtest=TestFireflyBulkLoaderCallEntrypointRemote -DfailIfNoTests=false --no-transfer-progress
  negative-test-bulk-loader-call-docker:
    name: Bulk Loader Call without Spark Fails
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCS_PRIVATE_KEY: ${{ secrets.GCS_PRIVATE_KEY }}
          GCS_PRIVATE_KEY_ID: ${{ secrets.GCS_PRIVATE_KEY_ID }}
          GCS_CLIENT_EMAIL: ${{ secrets.GCS_CLIENT_EMAIL }}
        run: |
          bash -x scripts/build-docker-stripped.sh aerospike/firefly linux/amd64
          
          docker run -p 8182:8182  \
            -v /home/runner/work/firefly/firefly/conf/docker-bulk-load/:/opt/aerospike-firefly/conf/ \
            -v /home/runner/work/firefly/firefly/data/docker-bulk-load/:/opt/aerospike-firefly/etc/ \
            aerospike/firefly &
          
          mvn test -pl aerospike-graph-gremlin -Dtest=TestFireflyBulkLoaderCallEntrypointRemoteFailsWithoutSpark -DfailIfNoTests=false --no-transfer-progress
  run-l3-bulk-loader:
    name: Run L3 Spark Bulk Loader
    timeout-minutes: 150
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clamp Start Time to Environment
        run: |
          echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "MONTH=$(date +%m)" >> $GITHUB_ENV
          echo "DAY=$(date +%d)" >> $GITHUB_ENV
      - name: Clamp SHA to Environment (Push)
        if: github.event_name == 'push'
        run: |
          echo "SHA_PATH=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Clamp SHA to Environment (Pull Request)
        if: github.event_name == 'pull_request'
        run : |
          echo "SHA_PATH=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_ENV
      - name: Authorize gcloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCS_KEYFILE_B64 }}
      - name: Set Up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Packages
        run: |
          sudo apt -y update
          sudo apt -y install wget
          sudo apt -y install jq
          sudo apt -y install python3
      - name: Download, Install, and Configure Aerolab
        run: |
          cd /tmp && wget https://github.com/aerospike/aerolab/releases/download/6.1.0/aerolab-linux-amd64-6.1.0.zip
          unzip aerolab-linux-amd64-6.1.0.zip -d /usr/local/bin/
          aerolab config backend -t gcp -o firefly-aerospike
      - name: Deploy Aerospike Cluster to GCP
        env:
          FEATURES_B64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
        run: |
          echo $FEATURES_B64 | base64 -d > ${{ github.workspace }}/scripts/features.conf
          cd ${{ github.workspace }}/scripts && ./provision-aerospike-gcp.sh -c 3 -n ${{ env.SHA_PATH }} -o ../.github/aerospike/aerospike_l3.conf -f ./features.conf
      - name: Generate Hosts List for Deployed Cluster
        run: |
          aerolab cluster list -j | jq '.' > ${{ github.workspace }}/scripts/clusters.json
          cd ${{ github.workspace }}/scripts && python3 generate_l3_config.py ${{ env.SHA_PATH }}
      - name: Deploy Firefly Client Machine to GCP
        run: |
          aerolab client create base --zone=us-central1-a --disk=pd-ssd:40 --instance n2d-standard-8 -n ${{ env.SHA_PATH }}-firefly
          cd ${{ github.workspace }}/.. && tar -zcvf firefly.tgz ./firefly
          cd ${{ github.workspace }}/.. && gcloud compute scp --zone=us-central1-a ./firefly.tgz aerolab4-${{ env.SHA_PATH }}-firefly-1:firefly.tgz
          cd ${{ github.workspace }}/scripts && gcloud compute scp --zone=us-central1-a ./run-benchmark-gcp.sh aerolab4-${{ env.SHA_PATH }}-firefly-1:run-benchmark-gcp.sh
      - name: Build Bulk Loader JAR
        run: |
          cd ${{ github.workspace }} && mvn clean install -DskipTests
          ls -l ${{ github.workspace }}/scripts
          cd aerospike-graph-bulk-loader/target && for f in aerospike-graph-bulk-loader*; do mv -- "$f" "aerospike-graph-bulk-loader.jar"; done
      - name: Upload Bulk Loading Artifacts to GCP
        run: |
          gcloud storage cp ${{ github.workspace }}/scripts/l3_config.properties gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/l3_config.properties
          gcloud storage cp ${{ github.workspace }}/aerospike-graph-bulk-loader/target/aerospike-graph-bulk-loader.jar gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/aerospike-graph-bulk-loader.jar
      - name: Run L3 Bulk Loading Job
        run: |
          cd ${{ github.workspace }}/scripts && ./bulk-load-dataproc.sh -n ci-${{ env.SHA_PATH }} -w 4 -j gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/aerospike-graph-bulk-loader.jar -c gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/l3_config.properties
      - name: Archive L3 Bulk Loading Job Log
        if: success() || failure()
        run: |
          cd ${{ github.workspace }}/scripts
          mkdir ${{ env.YEAR }}
          mkdir ${{ env.YEAR }}/${{ env.MONTH }}
          mkdir ${{ env.YEAR }}/${{ env.MONTH }}/${{ env.DAY }}
          mkdir ${{ env.YEAR }}/${{ env.MONTH }}/${{ env.DAY }}/${{ env.SHA_PATH }}
          gcloud dataproc jobs wait ci-${{ env.SHA_PATH }}-job --region 'us-central1'> ${{ env.YEAR }}/${{ env.MONTH }}/${{ env.DAY }}/${{ env.SHA_PATH }}/l3_job_metadata.txt 2>${{ env.YEAR }}/${{ env.MONTH }}/${{ env.DAY }}/${{ env.SHA_PATH }}/l3_job_log.txt
          gcloud storage mv gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/l3_config.properties gs://gha-ci-firefly-bulkloader/archive/${{ env.YEAR }}/${{ env.MONTH }}/${{ env.DAY }}/${{ env.SHA_PATH }}/l3_config.properties
      - name: Upload L3 Bulk Loading Job Log to GCP
        if: success() || failure()
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: ${{ github.workspace }}/scripts/${{ env.YEAR }}
          destination: gha-ci-firefly-bulkloader/archive
          gzip: false
          process_gcloudignore: false
      - name: Run Benchmark on GCP
        run: |
          gcloud compute ssh --zone=us-central1-a aerolab4-${{ env.SHA_PATH }}-firefly-1 -- "sudo bash run-benchmark-gcp.sh"
      - name: Upload Benchmark Results
        run: |
          gcloud compute ssh --zone=us-central1-a aerolab4-${{ env.SHA_PATH }}-firefly-1 -- "sudo cat ./firefly/aerospike-graph-gremlin/target/benchmark.json" > benchmark.json
          gcloud storage cp benchmark.json gs://gha-ci-firefly-bulkloader/archive/${{ env.YEAR }}/${{ env.MONTH }}/${{ env.DAY }}/${{ env.SHA_PATH }}/benchmark.json
      - name: Delete Firefly Compute Instances (Cleanup)
        if: always()
        run: |
          aerolab client destroy -f -n ${{ env.SHA_PATH }}-firefly
      - name: Delete Aerospike Compute Instances (Cleanup)
        if: always()
        run: |
          aerolab cluster destroy -f -n ${{ env.SHA_PATH }}
      - name: Delete Dataproc Clusters (Cleanup)
        if: always()
        run: |
          gcloud dataproc clusters delete --region us-central1 -q ci-${{ env.SHA_PATH }}
      - name: Delete Cloud Storage Artifacts (Cleanup)
        if: always()
        run: |
          gcloud storage rm -r gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}
  test-heap-usage:
    name: Test Firefly Heap Usage
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run Memory Leak Test
        run: |
          mvn test -pl aerospike-graph-gremlin -Dtest=TestFireflyServer -DfailIfNoTests=false --no-transfer-progress
      - name: Publish Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Publish Benchmark Results
          tool: 'customSmallerIsBetter'
          output-file-path: aerospike-graph-gremlin/target/jmh-result.json
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: '@lyndonbauto @cinterloper @DKZed'
          github-token: ${{ secrets.PUBLISH_BENCHMARKS_TOKEN }}
          benchmark-data-dir-path: docs/
  benchmark-firefly:
    name: Benchmark Firefly
    timeout-minutes: 240
    needs: start-runner-benchmark
    runs-on: ${{ needs.start-runner-benchmark.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Launch Firefly in Gremlin-Server and Run Benchmark
        run: |
          echo "Downloading gremlin-server"
          cd ..
          wget -O gremlin-server https://archive.apache.org/dist/tinkerpop/3.6.3/apache-tinkerpop-gremlin-server-3.6.3-bin.zip --quiet
          echo "Unzipping gremlin-server"
          unzip -qq gremlin-server
          
          echo "Build Firefly"
          cd firefly
          mvn clean install -DskipTests --no-transfer-progress
          
          echo "Installing Firefly in gremlin-server"
          ../apache-tinkerpop-gremlin-server-3.6.3/bin/gremlin-server.sh install 'com.aerospike aerospike-graph-gremlin 1.1.0-SNAPSHOT'
          
          echo "Starting gremlin-server"
          ../apache-tinkerpop-gremlin-server-3.6.3/bin/gremlin-server.sh /actions-runner/_work/firefly/firefly/conf/firefly-gremlin-server-github-actions.yaml &
          
          echo "Sleeping for 30 seconds while gremlin-server starts"
          sleep 30
          
          echo "Running benchmark"
          mvn test -pl aerospike-graph-gremlin -Dtest=BenchmarkTestFlightsData -DfailIfNoTests=false --no-transfer-progress
      - name: Publish Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Publish Benchmark Results
          tool: 'customSmallerIsBetter'
          output-file-path: aerospike-graph-gremlin/target/jmh-result.json
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: '@lyndonbauto @cinterloper @DKZed'
          github-token: ${{ secrets.PUBLISH_BENCHMARKS_TOKEN }}
          benchmark-data-dir-path: docs/
  test-firefly-tls:
    name: Test TLS integration
    timeout-minutes: 12
    needs: start-runner-tls
    runs-on: ${{ needs.start-runner-tls.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          sudo echo "172.17.0.1 aerospike.test.aerospike.dev" > /etc/hosts
          mvn -DskipTests clean compile test-compile package
          mvn -pl aerospike-graph-gremlin -Djavax.net.ssl.trustStore=$(realpath aerospike-graph-gremlin/src/test/resources/tls/trust-store.jks) -Djavax.net.ssl.keyStore=$(realpath aerospike-graph-gremlin/src/test/resources/tls/client.jks) -Djavax.net.ssl.trustStorePassword=abc123 -Djavax.net.ssl.keyStorePassword=abc123 -Dtest=TestTLSIntegration -Dintegration.test.properties=packed test --no-transfer-progress
  test-firefly-client-provider:
    name: Test Client Provider
    timeout-minutes: 12
    needs: start-runner-client-provider
    runs-on: ${{ needs.start-runner-client-provider.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          sudo echo "172.17.0.1 aerospike.test.aerospike.dev" > /etc/hosts
          mvn test -pl aerospike-graph-gremlin -Dtest=ConcurrentClientProviderInstantiationTest -DfailIfNoTests=false --no-transfer-progress
  test-firefly-packed:
    name: Test Packed
    timeout-minutes: 120
    needs: start-runner-packed
    runs-on: ${{ needs.start-runner-packed.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCS_PRIVATE_KEY: ${{ secrets.GCS_PRIVATE_KEY }}
          GCS_PRIVATE_KEY_ID: ${{ secrets.GCS_PRIVATE_KEY_ID }}
          GCS_CLIENT_EMAIL: ${{ secrets.GCS_CLIENT_EMAIL }}
        run: |
          sudo echo "172.17.0.1 aerospike.test.aerospike.dev" > /etc/hosts
          mvn -pl aerospike-graph-gremlin -Dintegration.test.properties=packed test --no-transfer-progress
  test-firefly-packed-lz4:
    name: Test Packed lz4
    timeout-minutes: 120
    needs: start-runner-packed-lz4
    runs-on: ${{ needs.start-runner-packed-lz4.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike_lz4.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCS_PRIVATE_KEY: ${{ secrets.GCS_PRIVATE_KEY }}
          GCS_PRIVATE_KEY_ID: ${{ secrets.GCS_PRIVATE_KEY_ID }}
          GCS_CLIENT_EMAIL: ${{ secrets.GCS_CLIENT_EMAIL }}
        run: |
          sudo echo "172.17.0.1 aerospike.test.aerospike.dev" > /etc/hosts
          mvn -pl aerospike-graph-gremlin -Dintegration.test.properties=packed test --no-transfer-progress
  test-firefly-packed-sindex:
    name: Test Packed Sindex
    timeout-minutes: 120
    needs: start-runner-packed-sindex
    runs-on: ${{ needs.start-runner-packed-sindex.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCS_PRIVATE_KEY: ${{ secrets.GCS_PRIVATE_KEY }}
          GCS_PRIVATE_KEY_ID: ${{ secrets.GCS_PRIVATE_KEY_ID }}
          GCS_CLIENT_EMAIL: ${{ secrets.GCS_CLIENT_EMAIL }}
        run: |
          sudo echo "172.17.0.1 aerospike.test.aerospike.dev" > /etc/hosts
          mvn -pl aerospike-graph-gremlin -Dintegration.test.properties=packed-sindex test --no-transfer-progress
  test-firefly-movielens-packed:
    name: Test Movielens Packed
    timeout-minutes: 120
    needs: start-runner-movielens-packed
    runs-on: ${{ needs.start-runner-movielens-packed.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          sudo echo "172.17.0.1 aerospike.test.aerospike.dev" > /etc/hosts
          mvn test -pl aerospike-graph-gremlin -Dtest=TestMovielens1M -DfailIfNoTests=false -Dintegration.test.properties=packed --no-transfer-progress
  test-firefly-small-memory-packed:
    name: Test Small Memory Packed
    timeout-minutes: 120
    needs: start-runner-small-memory-packed
    runs-on: ${{ needs.start-runner-small-memory-packed.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          sudo echo "172.17.0.1 aerospike.test.aerospike.dev" > /etc/hosts
          mvn test -pl aerospike-graph-gremlin -Dtest=TestFireflyExceedHeap -DfailIfNoTests=false -Dintegration.test.properties=packed -Djvmheapsize=small --no-transfer-progress
  test-firefly-aerospike-version-minimum:
    name: Test Aerospike Version Minimum
    timeout-minutes: 120
    needs: start-runner-aerospike-version-minimum
    runs-on: ${{ needs.start-runner-aerospike-version-minimum.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.3
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          sudo echo "172.17.0.1 aerospike.test.aerospike.dev" > /etc/hosts
          mvn test -pl aerospike-graph-gremlin -Dtest=FireflyAerospikeVersionCheckTest -DfailIfNoTests=false -Dintegration.test.properties=packed --no-transfer-progress
  test-firefly-invalid-feature-key:
    name: Test Aerospike Invalid Feature Key
    timeout-minutes: 120
    needs: start-runner-invalid-feature-key
    runs-on: ${{ needs.start-runner-invalid-feature-key.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE_WITHOUT_GRAPH_SERVICE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          sudo echo "172.17.0.1 aerospike.test.aerospike.dev" > /etc/hosts
          mvn test -pl aerospike-graph-gremlin -Dtest=FireflyAerospikeGraphServiceCheckTest -DfailIfNoTests=false -Dintegration.test.properties=packed --no-transfer-progress
  test-firefly-spark-bulk-loader:
    name: Test Spark Bulk Loader
    timeout-minutes: 30
    needs: start-runner-spark-bulk-loader
    runs-on: ${{ needs.start-runner-spark-bulk-loader.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCS_PRIVATE_KEY: ${{ secrets.GCS_PRIVATE_KEY }}
          GCS_PRIVATE_KEY_ID: ${{ secrets.GCS_PRIVATE_KEY_ID }}
          GCS_CLIENT_EMAIL: ${{ secrets.GCS_CLIENT_EMAIL }}
          GCS_KEYFILE_B64: ${{ secrets.GCS_KEYFILE_B64 }}
          GH_WORKSPACE: ${{ github.workspace}}
        run: |
          sudo echo $GCS_KEYFILE_B64 | base64 -d > ${{ github.workspace }}/gcs-keyfile.json
          mvn clean install -DskipTests
          mvn -pl aerospike-graph-bulk-loader test --no-transfer-progress
  test-firefly-spark-bulk-loader-lz4:
    name: Test Spark Bulk Loader lz4
    timeout-minutes: 30
    needs: start-runner-spark-bulk-loader-lz4
    runs-on: ${{ needs.start-runner-spark-bulk-loader-lz4.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike_lz4.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test with Maven
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCS_PRIVATE_KEY: ${{ secrets.GCS_PRIVATE_KEY }}
          GCS_PRIVATE_KEY_ID: ${{ secrets.GCS_PRIVATE_KEY_ID }}
          GCS_CLIENT_EMAIL: ${{ secrets.GCS_CLIENT_EMAIL }}
          GCS_KEYFILE_B64: ${{ secrets.GCS_KEYFILE_B64 }}
          GH_WORKSPACE: ${{ github.workspace}}
        run: |
          sudo echo $GCS_KEYFILE_B64 | base64 -d > ${{ github.workspace }}/gcs-keyfile.json
          mvn clean install -DskipTests
          mvn -pl aerospike-graph-bulk-loader test --no-transfer-progress
  benchmark-internal dataset-flow-firefly:
    name: Benchmark internal dataset Flow Firefly
    timeout-minutes: 240
    needs: start-runner-benchmark-internal dataset
    runs-on: ${{ needs.start-runner-benchmark-internal dataset.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Launch Firefly in Gremlin-Server and Run Benchmark
        run: |
          echo "Downloading gremlin-server"
          cd ..
          wget -O gremlin-server https://archive.apache.org/dist/tinkerpop/3.6.3/apache-tinkerpop-gremlin-server-3.6.3-bin.zip --quiet
          echo "Unzipping gremlin-server"
          unzip -qq gremlin-server

          echo "Build Firefly"
          cd firefly
          mvn clean install -DskipTests --no-transfer-progress

          echo "Installing Firefly in gremlin-server"
          ../apache-tinkerpop-gremlin-server-3.6.3/bin/gremlin-server.sh install 'com.aerospike aerospike-graph-gremlin 1.1.0-SNAPSHOT'

          echo "Starting gremlin-server"
          ../apache-tinkerpop-gremlin-server-3.6.3/bin/gremlin-server.sh /actions-runner/_work/firefly/firefly/conf/firefly-gremlin-server-github-actions.yaml &

          echo "Sleeping for 30 seconds while gremlin-server starts"
          sleep 30

          echo "Running benchmark"
          mvn test -pl aerospike-graph-gremlin -Dtest=BenchmarkTestSyntheticinternaldataset -DfailIfNoTests=false --no-transfer-progress
      - name: Publish Benchmark internal dataset Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Publish Benchmark Results
          tool: 'customSmallerIsBetter'
          output-file-path: aerospike-graph-gremlin/target/jmh-result.json
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: '@lyndonbauto @cinterloper @DKZed'
          github-token: ${{ secrets.PUBLISH_BENCHMARKS_TOKEN }}
          benchmark-data-dir-path: docs/
  benchmark-identifies-flow-firefly:
    name: Benchmark Identifies Flow Firefly
    timeout-minutes: 240
    needs: start-runner-benchmark-identifies
    runs-on: ${{ needs.start-runner-benchmark-identifies.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /actions-runner/_work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Launch Firefly in Gremlin-Server and Run Benchmark
        run: |
          echo "Downloading gremlin-server"
          cd ..
          wget -O gremlin-server https://archive.apache.org/dist/tinkerpop/3.6.3/apache-tinkerpop-gremlin-server-3.6.3-bin.zip --quiet
          echo "Unzipping gremlin-server"
          unzip -qq gremlin-server

          echo "Build Firefly"
          cd firefly
          mvn clean install -DskipTests --no-transfer-progress

          echo "Installing Firefly in gremlin-server"
          ../apache-tinkerpop-gremlin-server-3.6.3/bin/gremlin-server.sh install 'com.aerospike aerospike-graph-gremlin 1.1.0-SNAPSHOT'

          echo "Starting gremlin-server"
          ../apache-tinkerpop-gremlin-server-3.6.3/bin/gremlin-server.sh /actions-runner/_work/firefly/firefly/conf/firefly-gremlin-server-github-actions.yaml &

          echo "Sleeping for 30 seconds while gremlin-server starts"
          sleep 30

          echo "Running benchmark"
          mvn test -pl aerospike-graph-gremlin -Dtest=BenchmarkTestIdentifiesTraversal -DfailIfNoTests=false --no-transfer-progress
      - name: Publish Benchmark Identifies Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Publish Benchmark Results
          tool: 'customSmallerIsBetter'
          output-file-path: aerospike-graph-gremlin/target/jmh-result.json
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: '@lyndonbauto @cinterloper @DKZed'
          github-token: ${{ secrets.PUBLISH_BENCHMARKS_TOKEN }}
          benchmark-data-dir-path: docs/
  run-prometheus-test:
    name: Prometheus Runner
    timeout-minutes: 30
    needs: build-firefly-maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Launch Firefly in Gremlin-Server and Test Prometheus
        run: |
          echo "Starting gremlin-server"
          bash -x scripts/build-docker.sh firefly linux/amd64
          
          echo "Running docker image with custom yaml file"
          docker run -p 8182:8182 -p 9090:9090 -v /home/runner/work/firefly/firefly/conf/test-custom-configs:/opt/aerospike-firefly/conf firefly &
          echo "Sleeping for 30 seconds while gremlin-server starts"
          sleep 30

          echo "Running Prometheus Test"
          mvn test -pl aerospike-graph-gremlin -Dtest=PrometheusExporterTest -DfailIfNoTests=false --no-transfer-progress
  run-custom-prometheus-port-and-endpoint-test:
    name: Custom Prometheus Port And Endpoint Runner
    timeout-minutes: 30
    needs: build-firefly-maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Launch Firefly in Gremlin-Server and Test Prometheus
        run: |
          echo "Building docker image"
          bash -x scripts/build-docker.sh firefly linux/amd64
          
          echo "Running docker image with custom yaml file"
          docker run -p 8182:8182 -p 9191:9191 -v /home/runner/work/firefly/firefly/conf/test-custom-prometheus-configs:/opt/aerospike-firefly/conf firefly &
          echo "Sleeping for 30 seconds while gremlin-server starts"
          sleep 30

          echo "Running Prometheus Test"
          mvn test -pl aerospike-graph-gremlin -Dtest=CustomPrometheusExporterTest -DfailIfNoTests=false --no-transfer-progress
  test-docker-with-custom-yaml:
    name: Test Docker Image with Custom yaml
    timeout-minutes: 30
    needs: build-firefly-maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Launch Firefly Docker Image with Custom yaml
        run: |
          echo "Starting gremlin-server"
          bash -x scripts/build-docker.sh firefly linux/amd64
          
          
          echo "Running docker image with custom yaml file"
          docker run -p 8182:8182 -v /home/runner/work/firefly/firefly/conf/test-custom-configs:/opt/aerospike-firefly/conf firefly &
          echo "Sleeping for 30 seconds while gremlin-server starts"
          sleep 30
          
          echo "Running benchmark"
          mvn test -pl aerospike-graph-gremlin -Dtest=ValidConnectionTest -DfailIfNoTests=false --no-transfer-progress
  test-docker-with-custom-properties:
    name: Test Docker Image with Custom properties
    timeout-minutes: 30
    needs: build-firefly-maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: cinterloper/github-action-aerospike@v5
        with:
          server-version: ee-6.2.0.7
          feature-key-b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
          firefly-path: /home/runner/work/firefly/firefly
          config-file: '.github/aerospike/aerospike.conf'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Launch Firefly Docker Image with Custom properties
        run: |
          echo "Starting gremlin-server"
          bash -x scripts/build-docker.sh firefly linux/amd64
          
          echo "Running docker image with custom properties file"
          docker run -p 8182:8182 -v /home/runner/work/firefly/firefly/conf/test-custom-configs/firefly-graph.properties:/opt/aerospike-firefly/conf/firefly-graph.properties firefly &

          echo "Sleeping for 30 seconds while gremlin-server starts"
          sleep 30

          echo "Running benchmark"
          mvn test -pl aerospike-graph-gremlin -Dtest=ValidConnectionTest -DfailIfNoTests=false --no-transfer-progress
  stop-runner-movielens-packed:
    name: Stop Movielens Packed Runner
    needs:
      - test-firefly-movielens-packed
      - start-runner-movielens-packed
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-movielens-packed.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-movielens-packed.outputs.ec2-instance-id }}
  stop-runner-tls-packed:
    name: Stop TLS Runner
    needs:
      - start-runner-tls
      - test-firefly-tls
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-tls.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-tls.outputs.ec2-instance-id }}
  stop-runner-client-provider:
    name: Stop Client Provider Runner
    needs:
      - start-runner-client-provider
      - test-firefly-client-provider
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-client-provider.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-client-provider.outputs.ec2-instance-id }}
  stop-runner-small-memory-packed:
    name: Stop Small Memory Packed Runner
    needs:
      - test-firefly-small-memory-packed
      - start-runner-small-memory-packed
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-small-memory-packed.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-small-memory-packed.outputs.ec2-instance-id }}
  stop-runner-aerospike-version-minimum:
    name: Stop Aerospike Minimum Version Runner
    needs:
      - test-firefly-aerospike-version-minimum
      - start-runner-aerospike-version-minimum
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-aerospike-version-minimum.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-aerospike-version-minimum.outputs.ec2-instance-id }}
  stop-runner-invalid-feature-key:
    name: Stop Aerospike Minimum Version Runner
    needs:
      - test-firefly-invalid-feature-key
      - start-runner-invalid-feature-key
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-invalid-feature-key.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-invalid-feature-key.outputs.ec2-instance-id }}
  stop-runner-packed:
    name: Stop Packed Runner
    needs:
      - test-firefly-packed
      - start-runner-packed
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-packed.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-packed.outputs.ec2-instance-id }}
  stop-runner-packed-lz4:
    name: Stop Packed Runner lz4
    needs:
      - test-firefly-packed-lz4
      - start-runner-packed-lz4
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-packed-lz4.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-packed-lz4.outputs.ec2-instance-id }}
  stop-runner-packed-sindex:
    name: Stop Packed Sindex Runner
    needs:
      - test-firefly-packed-sindex
      - start-runner-packed-sindex
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-packed-sindex.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-packed-sindex.outputs.ec2-instance-id }}
  stop-runner-docker:
    name: Stop Docker Build Runner
    needs:
      - build-firefly-docker
      - start-runner-docker
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-docker.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-docker.outputs.ec2-instance-id }}
  stop-runner-benchmark:
    name: Stop Benchmark Runner
    needs:
      - benchmark-firefly
      - start-runner-benchmark
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-benchmark.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-benchmark.outputs.ec2-instance-id }}
  stop-runner-benchmark-internal dataset:
    name: Stop Benchmark internal dataset Runner
    needs:
      - benchmark-internal dataset-flow-firefly
      - start-runner-benchmark-internal dataset
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-benchmark-internal dataset.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-benchmark-internal dataset.outputs.ec2-instance-id }}
  stop-runner-benchmark-identifies:
    name: Stop Benchmark Identifies Runner
    needs:
      - benchmark-identifies-flow-firefly
      - start-runner-benchmark-identifies
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-benchmark-identifies.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-benchmark-identifies.outputs.ec2-instance-id }}
  stop-runner-spark-bulk-loader:
    name: Stop Spark Bulk Loader Runner
    needs:
      - test-firefly-spark-bulk-loader
      - start-runner-spark-bulk-loader
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-spark-bulk-loader.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-spark-bulk-loader.outputs.ec2-instance-id }}
  stop-runner-spark-bulk-loader-lz4:
    name: Stop Spark Bulk Loader Runner lz4
    needs:
      - test-firefly-spark-bulk-loader-lz4
      - start-runner-spark-bulk-loader-lz4
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-spark-bulk-loader-lz4.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-spark-bulk-loader-lz4.outputs.ec2-instance-id }}
