name: Publish Aerospike Graph Container for Dev to QE

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-qe-**'
    branches: [2.x-dev]

env:
  QE_DOCKER_REGISTRY: secure.docker.qe.aerospike.com
  QE_DOCKER_USERNAME: firefly

jobs:
  publish-github:
    name: Publish Firefly Docker Image - QE
    permissions:
      packages: write
      contents: read
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.QE_REGISTRY_PASSWORD }} | docker login $QE_DOCKER_REGISTRY --username $QE_DOCKER_USERNAME --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # For multiarch builds, we need to set up QEMU.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Publish Container
        run: |
          pip3 install python_on_whales
          
          # Strip git ref prefix (refs/tags or ref/heads).
          VERSION=$(git rev-parse --short "$GITHUB_SHA")
  
          # Get registry URL and convert to lower case.
          OUTPUT_IMAGE=$QE_DOCKER_REGISTRY/firefly:dev-$VERSION
          OUTPUT_IMAGE=$(echo $OUTPUT_IMAGE | tr '[A-Z]' '[a-z]')
          
          DOCKER_IMAGE=$QE_DOCKER_REGISTRY/firefly:dev
          DOCKER_IMAGE=$(echo $DOCKER_IMAGE | tr '[A-Z]' '[a-z]')
          
          echo "Building and tagging docker image for linux/amd64 $DOCKER_IMAGE $OUTPUT_IMAGE"
          docker buildx create --use --driver docker-container
          python3 scripts/build-docker.py --tags $DOCKER_IMAGE $OUTPUT_IMAGE --platform linux/amd64 linux/arm64 --push
          python3 scripts/build-docker.py --tags ${DOCKER_IMAGE}-slim ${OUTPUT_IMAGE}-slim --platform linux/amd64 linux/arm64 --push --slim
          
          echo "OUTPUT_IMAGE=$OUTPUT_IMAGE" >> $GITHUB_ENV
