name: Publish Firefly Container

# Publish the container if a tag of 'vX.Y.Z-rcW' is made.
# Example: v0.0.1-rc1, v0.1.0-rc2, v1.0.0-rc3, etc.
# THIS WILL NOT RUN ON TAGS WITHOUT A DASH IN THEM (release candidates only)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

env:
  VERSION: v0.0.0.0.1-rc1
  GITHUB_REPOSITORY_NAME: citrusleaf
  GITHUB_IMAGE_NAME: firefly
  GITHUB_REGISTRY_URL: ghcr.io

jobs:

  publish-github:
    name: Publish Firefly Docker Image - GitHub
    permissions:
      packages: write
      contents: read
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: |
          # Login to ghcr.io.
          echo ${{ secrets.CONTAINER_PUBLISH_PASSWORD }} | docker login $GITHUB_REGISTRY_URL --username ${{ secrets.CONTAINER_PUBLISH_USERNAME }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish Container
        run: |
          # Strip git ref prefix (refs/tags or ref/heads).
          VERSION="v0.0.0.0.1-rc1"
          #VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
  
          # Strip prefixed v if it is a tag.
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
  
          # Get registry URL and convert to lower case.
          OUTPUT_IMAGE=$GITHUB_REGISTRY_URL/$GITHUB_REPOSITORY_NAME/$GITHUB_IMAGE_NAME:$VERSION
          OUTPUT_IMAGE=$(echo $OUTPUT_IMAGE | tr '[A-Z]' '[a-z]')
          UNSTABLE_INDICATOR="-"
          if [[ $( echo $VERSION | grep -c -i $UNSTABLE_INDICATOR ) -eq 0 ]]; then
            DOCKER_IMAGE=$GITHUB_REGISTRY_URL/$GITHUB_REPOSITORY_NAME/$GITHUB_IMAGE_NAME:latest
            DOCKER_IMAGE=$(echo $DOCKER_IMAGE | tr '[A-Z]' '[a-z]')
            # Build and tag latest/unstable docker image. Note, we must push here since we cannot store the image in the cache since it isn't for our arch.
            echo "Building and tagging docker image for linux/amd64 and linux/arm64 $DOCKER_IMAGE $OUTPUT_IMAGE"
  
            export EXTRA_BUILD_ARGS="--build-arg RELEASE_BUILD=1"
            bash -x scripts/build-docker.sh $DOCKER_IMAGE linux/amd64 --push
            bash -x scripts/build-docker.sh $DOCKER_IMAGE linux/arm64 --push
            bash -x scripts/build-docker.sh $OUTPUT_IMAGE linux/amd64 --push
            bash -x scripts/build-docker.sh $OUTPUT_IMAGE linux/arm64 --push
          else
            DOCKER_IMAGE=$GITHUB_REGISTRY_URL/$GITHUB_REPOSITORY_NAME/$GITHUB_IMAGE_NAME:unstable
            DOCKER_IMAGE=$(echo $DOCKER_IMAGE | tr '[A-Z]' '[a-z]')
            # Build and tag latest/unstable docker image. Note, we must push here since we cannot store the image in the cache since it isn't for our arch.
            echo "Building and tagging docker image for linux/amd64 $DOCKER_IMAGE $OUTPUT_IMAGE"

            bash -x scripts/build-docker.sh $DOCKER_IMAGE linux/amd64 --push
            bash -x scripts/build-docker.sh $DOCKER_IMAGE linux/arm64 --push
            bash -x scripts/build-docker.sh $OUTPUT_IMAGE linux/amd64 --push
            bash -x scripts/build-docker.sh $OUTPUT_IMAGE linux/arm64 --push
          fi
          echo "OUTPUT_IMAGE=$OUTPUT_IMAGE" >> $GITHUB_ENV

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.OUTPUT_IMAGE }}

  publish-artifacts:
    name: Publish Artifacts
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Java 11 Install
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build Bulk Loader
      run: |
        mvn clean install -DskipTests

    - name: Upload Bulk Loader
      uses: actions/upload-artifact@v3
      with:
        path: aerospike-graph-bulk-loader/target/aerospike-graph-bulk-loader-*.jar
