name: Publish Firefly Container

# Publish the container if a tag of 'v*' is made.
# Example: v0.0.1, v0.1.0, v1.0.0, etc.
on:
  # TODO: Remove pull_request: branches: [main]. This is for testing only.
  pull_request:
    branches: [main]
  #push:
  #  tags:
  #    - 'v*'

env:
  REPOSITORY_NAME: aerospike
  IMAGE_NAME: firefly
  VERSION: v0.0.1

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    name: build-firefly-docker
    permissions:
      packages: write
      contents: read
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Container
        run: |
      # - if: $CI_PIPELINE_SOURCE == "push"
      # - name: Push Container
      #   run: |
      #     docker push $REPOSITORY_NAME/$IMAGE_NAME

      - name: Publish Container
        run: |
          # Login to ghcr.io.
          echo ${{ secrets.CONTAINER_PUBLISH_PASSWORD }} | docker login ghcr.io --username ${{ secrets.CONTAINER_PUBLISH_USERNAME }} --password-stdin
          
          # Get image id.
          IMAGE_ID=ghcr.io/$REPOSITORY_NAME/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # Strip git ref prefix from version
          # VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Strip "v" prefix from tag name
          # [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Use Docker `latest` tag convention
          # [ "$VERSION" == "main" ] && VERSION=latest
          
          # Print out the image id and version.
          VERSION=0.0.0-docker-test
          echo REPOSITORY_NAME=$REPOSITORY_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          
          echo "Building docker image"
          docker build -t $REPOSITORY_NAME/$IMAGE_NAME .
          
          # Create docker tag.
          echo "Creating docker tag"
          docker tag $IMAGE_NAME $REPOSITORY_NAME/$IMAGE_ID:$VERSION
          
          # Push Docker tag.
          echo "Pushing docker tag"
          docker push $REPOSITORY_NAME/$IMAGE_ID:$VERSION
