name: Publish Firefly Container

# Publish the container if a tag of 'v*' is made.
# Example: v0.0.1, v0.1.0, v1.0.0, etc.
on:
  # TODO: Remove pull_request: branches: [main]. This is for testing only.
  pull_request:
    branches: [main]
  #push:
  #  tags:
  #    - 'v*'

env:
  REPOSITORY_NAME: citrusleaf
  IMAGE_NAME: firefly
  VERSION: v0.0.1

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    name: build-firefly-docker
    permissions:
      packages: write
      contents: read
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: |
          # Login to ghcr.io.
          echo ${{ secrets.DOCKER_PUBLISH_USERNAME }} | docker login ghcr.io --username ${{ secrets.CONTAINER_PUBLISH_USERNAME }} --password-stdin

      - name: Publish Container
        run: |
          # Get image id.
          IMAGE_ID=ghcr.io/$REPOSITORY_NAME/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # Strip git ref prefix from version
          # VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Strip "v" prefix from tag name
          # [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Use Docker `latest` tag convention
          # [ "$VERSION" == "main" ] && VERSION=latest
          
          # Print out the image id and version.
          VERSION=0.0.0-docker-test
          
          # Build and tag docker image.
          echo "Building and tagging docker image"
          docker build --tag ghcr.io/$REPOSITORY_NAME/$IMAGE_NAME:$VERSION .
          
          # Push Docker tag.
          echo "Pushing docker tag"
          docker push ghcr.io/$REPOSITORY_NAME/$IMAGE_NAME:$VERSION
