name: Publish Aerospike Graph Container to Dockerhub and GCR

# Publish the container if a full release is made.
# See https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=released#release
# and https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
on:
  release:
    types: [released]

env:
  GITHUB_REPOSITORY_NAME: citrusleaf
  GITHUB_IMAGE_NAME: firefly
  GITHUB_REGISTRY_URL: ghcr.io
  DOCKERHUB_IMAGE_NAME: aerospike-graph-service
  DOCKERHUB_REPOSITORY_NAME: aerospike
  GCLOUD_REPOSITORY_NAME: gcr.io/aerospike-prod
  GCLOUD_IMAGE_NAME: aerospike-graph-service


jobs:
  publish-dockerhub:
    name: Publish Aerospike Graph Docker Image - Dockerhub
    permissions:
      packages: write
      contents: read
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Cloud Authentication
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_DOCKER_REPO_SECRET }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Login to Dockerhub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: aerospikebuildbot
          password: ${{ secrets.AEROSPIKEBUILDBOT }}

      - name: Login to GitHub Container Registry
        run: |
          # Login to ghcr.io.
          echo ${{ secrets.CONTAINER_PUBLISH_PASSWORD }} | docker login $GITHUB_REGISTRY_URL --username ${{ secrets.CONTAINER_PUBLISH_USERNAME }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # For multiarch builds, we need to set up QEMU.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Publish Container
        run: |
          # Configure docker auth for gcloud
          gcloud auth configure-docker -q
          
          # Strip git ref prefix (refs/tags or ref/heads).
          # From the release event structure, we expect to find it under this.
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Strip prefixed v if it is a tag.
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Find the release candidate number from ghcr.io.
          GITHUB_IMAGE_BASE=$GITHUB_REGISTRY_URL/$GITHUB_REPOSITORY_NAME/$GITHUB_IMAGE_NAME
          source ./scripts/find-release-candidate.sh docker manifest inspect $GITHUB_IMAGE_BASE:$VERSION || true
          
          GITHUB_IMAGE=$GITHUB_IMAGE_BASE:$VERSION-rc$DOCKER_RC_TAG
          GITHUB_IMAGE_ARM=${GITHUB_IMAGE}-arm64
          GITHUB_IMAGE_AMD=${GITHUB_IMAGE}-amd64
          
          GITHUB_IMAGE=$GITHUB_IMAGE_BASE:$VERSION-rc$DOCKER_RC_TAG
          GITHUB_IMAGE_ARM_SLIM=${GITHUB_IMAGE}-slim-arm64
          GITHUB_IMAGE_AMD_SLIM=${GITHUB_IMAGE}-slim-amd64
          
          # Get registry URL and convert to lower case.
          DOCKERHUB_IMAGE_BASE=$DOCKERHUB_REPOSITORY_NAME/$DOCKERHUB_IMAGE_NAME
          GCLOUD_IMAGE_BASE=$GCLOUD_REPOSITORY_NAME/$GCLOUD_IMAGE_NAME
          
          DOCKERHUB_IMAGE_BASE=$DOCKERHUB_REPOSITORY_NAME/$DOCKERHUB_IMAGE_NAME
          DOCKERHUB_OUTPUT_IMAGE=$DOCKERHUB_IMAGE_BASE:$VERSION
          DOCKERHUB_OUTPUT_IMAGE=$(echo $DOCKERHUB_OUTPUT_IMAGE | tr '[A-Z]' '[a-z]')
          DOCKERHUB_LATEST_IMAGE=$DOCKERHUB_IMAGE_BASE:latest
          DOCKERHUB_LATEST_IMAGE=$(echo $DOCKERHUB_LATEST_IMAGE | tr '[A-Z]' '[a-z]')
          DOCKERHUB_IMMUTABLE_IMAGE=${DOCKERHUB_OUTPUT_IMAGE}.1
          
          # Set gcloud output and latest image name.
          # 2.4.1-slim
          GCLOUD_OUTPUT_IMAGE_SLIM=$GCLOUD_IMAGE_BASE:$VERSION-slim
          #2.4.1-slim
          GCLOUD_OUTPUT_IMAGE_SLIM=$(echo GCLOUD_OUTPUT_IMAGE_SLIM | tr '[A-Z]' '[a-z]')
          #latest-slim
          GCLOUD_LATEST_IMAGE_SLIM=$GCLOUD_IMAGE_BASE:latest-slim
          GCLOUD_LATEST_IMAGE_SLIM=$(echo GCLOUD_LATEST_IMAGE_SLIM | tr '[A-Z]' '[a-z]')
          #2.4.1-slim.1
          GCLOUD_IMMUTABLE_IMAGE_SLIM=${GCLOUD_OUTPUT_IMAGE_SLIM}.1
          
          # 2.4.1-slim
          DOCKERHUB_OUTPUT_IMAGE_SLIM=$DOCKERHUB_IMAGE_BASE:$VERSION-slim
          #2.4.1-slim
          DOCKERHUB_OUTPUT_IMAGE_SLIM=$(echo DOCKERHUB_OUTPUT_IMAGE_SLIM | tr '[A-Z]' '[a-z]')
          #latest-slim
          DOCKERHUB_LATEST_IMAGE_SLIM=$DOCKERHUB_IMAGE_BASE:latest-slim
          DOCKERHUB_LATEST_IMAGE_SLIM=$(echo DOCKERHUB_LATEST_IMAGE_SLIM | tr '[A-Z]' '[a-z]')
          #2.4.1-slim.1
          DOCKERHUB_IMMUTABLE_IMAGE=${DOCKERHUB_OUTPUT_IMAGE_SLIM}.1
          
          # Pull base image.
          docker pull ${GITHUB_IMAGE_ARM} --platform linux/arm64
          docker pull ${GITHUB_IMAGE_AMD} --platform linux/amd64
          docker pull ${GITHUB_IMAGE_ARM_SLIM} --platform linux/arm64
          docker pull ${GITHUB_IMAGE_AMD_SLIM} --platform linux/amd64
          
          docker buildx imagetools create -t ${DOCKERHUB_OUTPUT_IMAGE} ${GITHUB_IMAGE_AMD} ${GITHUB_IMAGE_ARM}
          docker buildx imagetools create -t ${DOCKERHUB_LATEST_IMAGE} ${GITHUB_IMAGE_AMD} ${GITHUB_IMAGE_ARM}
          docker buildx imagetools create -t ${DOCKERHUB_IMMUTABLE_IMAGE} ${GITHUB_IMAGE_AMD} ${GITHUB_IMAGE_ARM}
          
          docker buildx imagetools create -t ${DOCKERHUB_OUTPUT_IMAGE_SLIM} ${GITHUB_IMAGE_AMD_SLIM} ${GITHUB_IMAGE_ARM_SLIM}
          docker buildx imagetools create -t ${DOCKERHUB_LATEST_IMAGE_SLIM} ${GITHUB_IMAGE_AMD_SLIM} ${GITHUB_IMAGE_ARM_SLIM}
          docker buildx imagetools create -t ${DOCKERHUB_IMMUTABLE_IMAGE_SLIM} ${GITHUB_IMAGE_AMD_SLIM} ${GITHUB_IMAGE_ARM_SLIM}
          
          docker buildx imagetools create -t ${GCLOUD_OUTPUT_IMAGE} ${GITHUB_IMAGE_AMD} ${GITHUB_IMAGE_ARM}
          docker buildx imagetools create -t ${GCLOUD_LATEST_IMAGE} ${GITHUB_IMAGE_AMD} ${GITHUB_IMAGE_ARM}
          docker buildx imagetools create -t ${GCLOUD_IMMUTABLE_IMAGE} ${GITHUB_IMAGE_AMD} ${GITHUB_IMAGE_ARM}
          
          docker buildx imagetools create -t ${GCLOUD_OUTPUT_IMAGE_SLIM} ${GITHUB_IMAGE_AMD_SLIM} ${GITHUB_IMAGE_ARM_SLIM}
          docker buildx imagetools create -t ${GCLOUD_LATEST_IMAGE_SLIM} ${GITHUB_IMAGE_AMD_SLIM} ${GITHUB_IMAGE_ARM_SLIM}
          docker buildx imagetools create -t ${GCLOUD_IMMUTABLE_IMAGE_SLIM} ${GITHUB_IMAGE_AMD_SLIM} ${GITHUB_IMAGE_ARM_SLIM}
