# Copyright 2022-2026 Aerospike, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish Public Release

# Publish the container if a full release is made.
# See https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=released#release
# and https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
on:
  release:
    types: [released]

env:
  GITHUB_REPOSITORY_NAME: ${{ github.repository_owner }}
  GITHUB_IMAGE_NAME: firefly
  GITHUB_REGISTRY_URL: ghcr.io
  DOCKERHUB_IMAGE_NAME: aerospike-graph-service
  DOCKERHUB_REPOSITORY_NAME: aerospike


jobs:
  publish-dockerhub:
    name: Publish Aerospike Graph Docker Image - Dockerhub
    permissions:
      packages: write
      contents: read
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: block

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Login to Dockerhub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: aerospikebuildbot
          password: ${{ secrets.AEROSPIKEBUILDBOT }}

      - name: Login to GitHub Container Registry
        run: |
          # Login to ghcr.io.
          echo ${{ secrets.GITHUB_TOKEN }} | docker login $GITHUB_REGISTRY_URL --username ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: step-security/setup-buildx-action@f931205d68723ad9589fd2a7e2ece238bf9de341 # v4.0.0

        # For multiarch builds, we need to set up QEMU.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

      - name: Publish Container
        run: |
          # Strip git ref prefix (refs/tags or ref/heads).
          # From the release event structure, we expect to find it under this.
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Strip prefixed v if it is a tag.
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          # Find the release candidate number from ghcr.io.
          GITHUB_IMAGE_BASE=$GITHUB_REGISTRY_URL/$GITHUB_REPOSITORY_NAME/$GITHUB_IMAGE_NAME
          source ./scripts/find-release-candidate.sh docker manifest inspect $GITHUB_IMAGE_BASE:$VERSION || true
          
          GITHUB_IMAGE=$GITHUB_IMAGE_BASE:$VERSION-rc$DOCKER_RC_TAG
          GITHUB_IMAGE_ARM=${GITHUB_IMAGE}-arm64
          GITHUB_IMAGE_AMD=${GITHUB_IMAGE}-amd64
          GITHUB_IMAGE_ARM_SLIM=${GITHUB_IMAGE}-slim-arm64
          GITHUB_IMAGE_AMD_SLIM=${GITHUB_IMAGE}-slim-amd64
          
          DOCKERHUB_IMAGE_BASE=$DOCKERHUB_REPOSITORY_NAME/$DOCKERHUB_IMAGE_NAME
          DOCKERHUB_IMAGE_BASE=$(echo $DOCKERHUB_IMAGE_BASE | tr '[A-Z]' '[a-z]')
          
          DOCKERHUB_OUTPUT_IMAGE=$DOCKERHUB_IMAGE_BASE:$VERSION
          DOCKERHUB_OUTPUT_IMAGE_SLIM=$DOCKERHUB_IMAGE_BASE:$VERSION-slim
          DOCKERHUB_LATEST_IMAGE=$DOCKERHUB_IMAGE_BASE:latest
          DOCKERHUB_LATEST_IMAGE_SLIM=$DOCKERHUB_IMAGE_BASE:latest-slim
          DOCKERHUB_IMMUTABLE_IMAGE=${DOCKERHUB_OUTPUT_IMAGE}.1
          DOCKERHUB_IMMUTABLE_IMAGE_SLIM=${DOCKERHUB_OUTPUT_IMAGE_SLIM}.1
          
          # Pull base image.
          docker pull ${GITHUB_IMAGE_ARM} --platform linux/arm64
          docker pull ${GITHUB_IMAGE_AMD} --platform linux/amd64
          docker pull ${GITHUB_IMAGE_ARM_SLIM} --platform linux/arm64
          docker pull ${GITHUB_IMAGE_AMD_SLIM} --platform linux/amd64
          
          docker buildx imagetools create -t ${DOCKERHUB_OUTPUT_IMAGE} ${GITHUB_IMAGE_AMD} ${GITHUB_IMAGE_ARM}
          docker buildx imagetools create -t ${DOCKERHUB_LATEST_IMAGE} ${GITHUB_IMAGE_AMD} ${GITHUB_IMAGE_ARM}
          docker buildx imagetools create -t ${DOCKERHUB_IMMUTABLE_IMAGE} ${GITHUB_IMAGE_AMD} ${GITHUB_IMAGE_ARM}
          
          docker buildx imagetools create -t ${DOCKERHUB_OUTPUT_IMAGE_SLIM} ${GITHUB_IMAGE_AMD_SLIM} ${GITHUB_IMAGE_ARM_SLIM}
          docker buildx imagetools create -t ${DOCKERHUB_LATEST_IMAGE_SLIM} ${GITHUB_IMAGE_AMD_SLIM} ${GITHUB_IMAGE_ARM_SLIM}
          docker buildx imagetools create -t ${DOCKERHUB_IMMUTABLE_IMAGE_SLIM} ${GITHUB_IMAGE_AMD_SLIM} ${GITHUB_IMAGE_ARM_SLIM}
