name: Publish Aerospike Graph Container to Dockerhub and GCR

# Publish the container if a full release is made.
# See https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=released#release
# and https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
on:
  push:
    branches: [2.4.0-rc4]

env:
  GITHUB_REPOSITORY_NAME: citrusleaf
  GITHUB_IMAGE_NAME: firefly
  GITHUB_REGISTRY_URL: ghcr.io
  DOCKERHUB_IMAGE_NAME: aerospike-graph-service
  DOCKERHUB_REPOSITORY_NAME: aerospike
  GCLOUD_REPOSITORY_NAME: gcr.io/aerospike-prod
  GCLOUD_IMAGE_NAME: aerospike-graph-service


jobs:
  publish-dockerhub:
    name: Publish Aerospike Graph Docker Image - Dockerhub
    permissions:
      packages: write
      contents: read
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Cloud Authentication
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_DOCKER_REPO_SECRET }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Login to Dockerhub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: aerospikebuildbot
          password: ${{ secrets.AEROSPIKEBUILDBOT }}

      - name: Login to GitHub Container Registry
        run: |
          # Login to ghcr.io.
          echo ${{ secrets.CONTAINER_PUBLISH_PASSWORD }} | docker login $GITHUB_REGISTRY_URL --username ${{ secrets.CONTAINER_PUBLISH_USERNAME }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # For multiarch builds, we need to set up QEMU.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Publish Container
        run: |
          VERSION=2.4.0
          GITHUB_IMAGE=ghcr.io/citrusleaf/firefly:2.4.0-r4
          DOCKERHUB_IMAGE_BASE=$DOCKERHUB_REPOSITORY_NAME/$DOCKERHUB_IMAGE_NAME
          DOCKERHUB_OUTPUT_IMAGE=$DOCKERHUB_IMAGE_BASE:$VERSION
          DOCKERHUB_OUTPUT_IMAGE=$(echo $DOCKERHUB_OUTPUT_IMAGE | tr '[A-Z]' '[a-z]')
          DOCKERHUB_LATEST_IMAGE=$DOCKERHUB_IMAGE_BASE:latest
          DOCKERHUB_LATEST_IMAGE=$(echo $DOCKERHUB_LATEST_IMAGE | tr '[A-Z]' '[a-z]')
        
          # Pull base image.
          docker pull $GITHUB_IMAGE --platform linux/arm64
          docker pull $GITHUB_IMAGE --platform linux/amd64
          
          docker tag $GITHUB_IMAGE ghcr.io/citrusleaf/firefly:foo-test
          docker push ghcr.io/citrusleaf/firefly:foo-test
