# Copyright 2022-2026 Aerospike, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: L3 Bulk Load and Benchmark Tag

on:
  push:
    tags:
      - '**-benchmark-[0-9a-zA-Z]+-[0-9]+g**'

jobs:
  start-runner-l3-bulk-loader:
    name: Start L3 Bulk Loader Runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@fcfb31a5760dad1314a64a0e172b78ec6fc8a17e # v2.3.6
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0d006286a6209f4bc
          ec2-instance-type: c7i.xlarge
          subnet-id: subnet-0bdbb4255fbffb239
          security-group-id: sg-005fce4b475465f9e
  run-l3-bulk-loader:
    name: Run L3 Spark Bulk Loader
    timeout-minutes: 3000
    runs-on: ${{ needs.start-runner-l3-bulk-loader.outputs.label }}
    needs: start-runner-l3-bulk-loader
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Install Packages
        run: |
          sudo apt -y update
          sudo apt -y install wget
          sudo apt -y install jq
          sudo apt -y install python3
      - name: Generate Properties File from Benchmark Tag
        run: |
          sudo python3 scripts/parse_benchmark_tag.py ${{ github.ref_name }}
      - name: Read Workflow Configuration from Properties File
        id: read_property
        uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b # 1.1.1
        with:
          path: benchmark.properties
          properties: 'data-size server-instances instance-type benchmark ssd-count storage-type tag-hash'
      - name: Clamp Runtime Variables to Environment
        run: |
          echo "SHA_PATH=${{ steps.read_property.outputs.tag-hash }}" >> $GITHUB_ENV
      - name: Authorize gcloud CLI
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCS_KEYFILE_B64 }}
      - name: Set Up gcloud CLI
        uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b # v1.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: step-security/setup-maven@8b5f727904660c4b112d02624218c791126af325 # v5.0.0
        with:
          maven-version: 3.9.5
      - run: mkdir -p /home/runner && chmod -R 777 /home/runner
      - run: echo "HOME=/home/runner" >> $GITHUB_ENV
      - name: Download Benchmark Configuration from GCP
        run: |
          gcloud storage cp gs://incremental-datasets/${{ steps.read_property.outputs.benchmark }}/config_base.properties ${{ github.workspace }}/scripts/l3_config_base.properties
          gcloud storage cp gs://incremental-datasets/${{ steps.read_property.outputs.benchmark }}/benchmark_name.txt ${{ github.workspace }}/benchmark_name.txt
      - name: Download, Install, and Configure Aerolab
        run: |
          cd /tmp && wget https://github.com/aerospike/aerolab/releases/download/7.3.0/aerolab-linux-amd64-7.3.0.zip
          unzip aerolab-linux-amd64-7.3.0.zip -d /usr/local/bin/
          aerolab config backend -t gcp -o firefly-aerospike
      - name: Deploy Aerospike Cluster to GCP
        env:
          FEATURES_B64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
        run: |
          echo $FEATURES_B64 | base64 -d > ${{ github.workspace }}/scripts/features.conf
          cd ${{ github.workspace }}/scripts && ./provision-aerospike-gcp.sh -i ${{ steps.read_property.outputs.instance-type }} -a ${{ steps.read_property.outputs.storage-type }} -s ${{ steps.read_property.outputs.ssd-count }} -c ${{ steps.read_property.outputs.server-instances }} -n ${{ env.SHA_PATH }} -o ../.github/aerospike/aerospike_l3.conf -f ./features.conf
      - name: Generate Hosts List and Config for Deployed Cluster
        run: |
          aerolab cluster list -j | jq '.' > ${{ github.workspace }}/scripts/clusters.json
          cd ${{ github.workspace }}/scripts && python3 generate_l3_config.py ${{ env.SHA_PATH }} ${{ steps.read_property.outputs.data-size }} ${{ steps.read_property.outputs.benchmark }}
          cd ${{ github.workspace }} && gcloud storage cp ${{ github.workspace }}/benchmark.properties gs://gha-ci-firefly-bulkloader/archive/${{ github.ref_name }}/ci.properties
      - name: Deploy Firefly Client Machine to GCP
        run: |
          aerolab client create none --zone=us-central1-a --disk=pd-ssd:40 --instance n2d-standard-8 -n ${{ env.SHA_PATH }}-firefly
          cd ${{ github.workspace }} && echo ${{ steps.read_property.outputs.data-size }} >> data_size.txt
          cd ${{ github.workspace }} && echo ${{ steps.read_property.outputs.storage-type }} >> storage_type.txt
          cd ${{ github.workspace }}/.. && tar -zcvf firefly.tgz ./firefly
          cd ${{ github.workspace }}/.. && gcloud compute scp --zone=us-central1-a ./firefly.tgz aerolab4-${{ env.SHA_PATH }}-firefly-1:firefly.tgz
          cd ${{ github.workspace }}/scripts && gcloud compute scp --zone=us-central1-a ./run-benchmark-gcp.sh aerolab4-${{ env.SHA_PATH }}-firefly-1:run-benchmark-gcp.sh
      - name: Build Bulk Loader JAR
        run: |
          cd ${{ github.workspace }} && mvn clean install -DskipTests
          cd aerospike-graph-bulk-loader/target && for f in aerospike-graph-bulk-loader*; do mv -- "$f" "aerospike-graph-bulk-loader.jar"; done
      - name: Upload Bulk Loading Artifacts to GCP
        run: |
          gcloud storage cp ${{ github.workspace }}/scripts/l3_config.properties gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/l3_config.properties
          gcloud storage cp ${{ github.workspace }}/aerospike-graph-bulk-loader/target/aerospike-graph-bulk-loader.jar gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/aerospike-graph-bulk-loader.jar
      - name: Run L3 Bulk Loading Job
        run: |
          cd ${{ github.workspace }}/scripts && ./bulk-load-dataproc.sh -n ci-${{ env.SHA_PATH }} -w 4 -j gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/aerospike-graph-bulk-loader.jar -c gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/l3_config.properties
          cd ${{ github.workspace }} && jq -n --arg name L3_${{ steps.read_property.outputs.data-size }}_${{ steps.read_property.outputs.storage-type }}_${{ steps.read_property.outputs.instance-type }}_${{ steps.read_property.outputs.server-instances }}-node --arg runtime $(cat ./scripts/l3_runtime.txt) '[{"name":$name, "unit":"Minutes", "value":$runtime|tonumber}]' > l3_benchmark.json
          gcloud storage cp ${{ github.workspace }}/l3_benchmark.json gs://gha-ci-firefly-bulkloader/archive/${{ github.ref_name }}/l3_benchmark.json
      - name: Archive L3 Bulk Loading Job Log
        if: success() || failure()
        run: |
          cd ${{ github.workspace }}/scripts
          mkdir ${{ github.ref_name }}
          gcloud dataproc jobs wait ci-${{ env.SHA_PATH }}-job --region 'us-central1'> ${{ github.ref_name }}/l3_job_metadata.txt 2>${{ github.ref_name }}/l3_job_log.txt
          gcloud storage mv gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}/l3_config.properties gs://gha-ci-firefly-bulkloader/archive/${{ github.ref_name }}/l3_config.properties
      - name: Upload L3 Bulk Loading Job Log to GCP
        if: success() || failure()
        uses: google-github-actions/upload-cloud-storage@e95a15f226403ed658d3e65f40205649f342ba2c # v1.0.3
        with:
          path: ${{ github.workspace }}/scripts/${{ github.ref_name }}
          destination: gha-ci-firefly-bulkloader/archive
          gzip: false
          process_gcloudignore: false
      - name: Publish L3 Runtime Results
        uses: benchmark-action/github-action-benchmark@4bdcce38c94cec68da58d012ac24b7b1155efe8b # v1.20.7
        with:
          name: Publish Benchmark Results
          tool: 'customSmallerIsBetter'
          output-file-path: l3_benchmark.json
          auto-push: true
          alert-threshold: '125%'
          comment-on-alert: true
          fail-on-alert: false
          github-token: ${{ secrets.PUBLISH_BENCHMARKS_TOKEN }}
          benchmark-data-dir-path: docs/
      - name: Run Benchmark on GCP
        run: |
          gcloud compute ssh --zone=us-central1-a aerolab4-${{ env.SHA_PATH }}-firefly-1 -- "sudo bash run-benchmark-gcp.sh"
      - name: Upload Benchmark Results
        run: |
          gcloud compute ssh --zone=us-central1-a aerolab4-${{ env.SHA_PATH }}-firefly-1 -- "sudo cat ./firefly/aerospike-graph-gremlin/target/benchmark.json" > ${{ github.workspace }}/aerospike-graph-gremlin/target/benchmark.json
          gcloud storage cp ${{ github.workspace }}/aerospike-graph-gremlin/target/benchmark.json gs://gha-ci-firefly-bulkloader/archive/${{ github.ref_name }}/benchmark.json
      - name: Publish Benchmark Results
        uses: benchmark-action/github-action-benchmark@4bdcce38c94cec68da58d012ac24b7b1155efe8b # v1.20.7
        with:
          name: Publish Benchmark Results
          tool: 'customSmallerIsBetter'
          output-file-path: aerospike-graph-gremlin/target/benchmark.json
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
          fail-on-alert: false
          github-token: ${{ secrets.PUBLISH_BENCHMARKS_TOKEN }}
          benchmark-data-dir-path: docs/
      - name: Log Aerospike Server on Failure
        if: failure()
        run: |
          aerolab logs get -n ${{ env.SHA_PATH }} --journal
          gcloud storage mv logs gs://gha-ci-firefly-bulkloader/archive/${{ github.ref_name }}/aerospike-server-log
      - name: Delete Firefly Compute Instances (Cleanup)
        if: always()
        run: |
          aerolab client destroy -f -n ${{ env.SHA_PATH }}-firefly
      - name: Delete Aerospike Compute Instances (Cleanup)
        if: always()
        run: |
          aerolab cluster destroy -f -n ${{ env.SHA_PATH }}
      - name: Delete Dataproc Clusters (Cleanup)
        if: always()
        run: |
          gcloud dataproc clusters delete --region us-central1 -q ci-${{ env.SHA_PATH }}
      - name: Delete Dataproc Job (Cleanup)
        if: always()
        run: |
          gcloud dataproc jobs delete --region us-central1 -q ci-${{ env.SHA_PATH }}-job
      - name: Delete Cloud Storage Artifacts (Cleanup)
        if: always()
        run: |
          gcloud storage rm -r gs://gha-ci-firefly-bulkloader/${{ env.SHA_PATH }}
  stop-runner-l3-bulk-loader:
    name: Stop Spark Bulk Loader Runner
    needs:
      - run-l3-bulk-loader
      - start-runner-l3-bulk-loader
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@fcfb31a5760dad1314a64a0e172b78ec6fc8a17e # v2.3.6
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner-l3-bulk-loader.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-l3-bulk-loader.outputs.ec2-instance-id }}
