# Copyright 2022-2026 Aerospike, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Tinkerbench Benchmark

on:
  schedule:
    # 8:00 AM UTC every Monday
    - cron: '0 8 * * 1'
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - 'tinkerbench-**'

env:
  features_b64: ${{ secrets.AEROSPIKE_DEV_LICENSE }}
  aerospike_count: 3
  aerospike_instance: n2d-highmem-16
  aerospike_version: 7.0.*
  aerospike_ssd_count: 2
  features_file: ${{ github.workspace }}/.github/aerospike/features.conf
  custom_conf: ${{ github.workspace }}/.github/aerospike/aerospike-rf1.conf
  graph_count: 1
  graph_instance_type: n2d-highcpu-8
  graph_disk_size: 50
  client_count: 1
  client_instance_type: n2d-highcpu-16
  client_disk_size: 50
  region: us-central1
  zone: us-central1-a
  dataproc_instance_type: n2d-highmem-16
  num_workers: 10
  project: firefly-aerospike
  aerobot-pw: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  tinkerbench-benchmark:
    name: Tinkerbench Benchmark
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Authorize gcloud CLI
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCS_KEYFILE_B64 }}

      - name: Download, Install, and Configure Aerolab
        run: |
          cd /tmp && wget https://github.com/aerospike/aerolab/releases/download/7.3.0/aerolab-linux-amd64-7.3.0.zip
          unzip aerolab-linux-amd64-7.3.0.zip -d /usr/local/bin/
          aerolab config backend -t gcp -o firefly-aerospike

      - name: Set Up gcloud CLI
        uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b # v1.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: step-security/setup-maven@8b5f727904660c4b112d02624218c791126af325 # v5.0.0
        with:
          maven-version: 3.9.5

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0

      - uses: Kaven-Universe/github-action-current-date-time@f2c12d90cff9c3e7b1f50430886e632fe31fcee1 # v1.4.0
        id: date_format
        with:
          format: "yyyy-MM-dd"

      - name: Clamp Runtime Variables to Environment
        run: |
          description_val=${{ steps.date_format.outputs.year }}${{ steps.date_format.outputs.month }}${{ steps.date_format.outputs.day }}${{steps.date_format.outputs.seconds}}
          bulk_jar_ui_val=gs://gha-ci-firefly-bulkloader/weekly-benchmark/${description_val}-perf/aerospike-graph-bulk-loader.jar
          properties_file_uri_val=gs://gha-ci-firefly-bulkloader/weekly-benchmark/${description_val}-perf/ags-properties.conf
          aerospike_name_val=tb-${description_val}-as
          dataproc_name_val=tb-${description_val}-dproc
          ags_image_val=ghcr.io/${{ github.repository_owner }}/firefly:${description_val}
          benchmark_client_name_val=tb-${description_val}-lg
          graph_name_val=tb-${description_val}-ags
          echo "description=${description_val}" >> $GITHUB_ENV
          echo "bulk_jar_uri=${bulk_jar_ui_val}" >> $GITHUB_ENV
          echo "properties_file_uri=${properties_file_uri_val}" >> $GITHUB_ENV
          echo "aerospike_name=${aerospike_name_val}" >> $GITHUB_ENV
          echo "dataproc_name=${dataproc_name_val}" >> $GITHUB_ENV
          echo "ags_image=${ags_image_val}" >> $GITHUB_ENV
          echo "benchmark_client_name=${benchmark_client_name_val}" >> $GITHUB_ENV
          echo "graph_name=${graph_name_val}" >> $GITHUB_ENV

      - name: Deploy to GCP and Bulk Load
        run: |
          # Build image.
          mvn clean install -DskipTests --no-transfer-progress
          pip3 install python_on_whales
          python3 scripts/build-docker.py --use_local --tags ${{ env.ags_image }} --platforms linux/amd64 --push

          # Copy bulk loader artifact to GCS.
          gcloud storage cp \
            ${{ github.workspace }}/aerospike-graph-bulk-loader/target/aerospike-graph-bulk-loader-*.jar \
            ${{ env.bulk_jar_uri }}
          
          # Create Aerospike cluster.
          echo ${{ env.features_b64 }} | base64 -d > ${{ env.features_file }}
          aerolab cluster create \
            --zone ${{env.zone}} \
            --name "${{ env.aerospike_name }}" \
            --count "${{ env.aerospike_count }}" \
            --instance "${{ env.aerospike_instance }}" \
            --aerospike-version "${{ env.aerospike_version }}" \
            --featurefile "${{ env.features_file }}" \
            --customconf "${{ env.custom_conf }}" \
            --disk pd-ssd:20 \
            --disk local-ssd@"${{ env.aerospike_ssd_count }}" \
            --start n
          
          # Partition cluster disks.
          aerolab cluster partition create \
            --name "${{ env.aerospike_name }}" \
            --filter-type nvme \
            --partitions 24,24,24,24
          
          aerolab cluster partition conf \
            --name "${{ env.aerospike_name }}" \
            --namespace test \
            --filter-type nvme \
            --filter-partitions 1,2,3,4 \
            --configure device
          
          # Start cluster.
          aerolab aerospike start --name="${{ env.aerospike_name }}"
          
          aerolab cluster list -j | jq '.' > ${{ github.workspace }}/clusters.json
          python3 ${{ github.workspace }}/scripts/generate_bulk_load_config.py ${{ env.aerospike_name }} ${{ github.workspace }}/benchmark-bulk-load-config.properties
          gcloud storage cp \
            ${{ github.workspace }}/benchmark-bulk-load-config.properties \
            ${{ env.properties_file_uri }}

          # Execute the dataproc command
          gcloud dataproc clusters create "${{ env.dataproc_name }}" \
            --enable-component-gateway \
            --region ${{ env.region }} \
            --zone ${{ env.zone }} \
            --master-machine-type "${{ env.dataproc_instance_type }}" \
            --master-boot-disk-type pd-ssd \
            --master-boot-disk-size 500 \
            --num-workers "${{ env.num_workers }}" \
            --worker-machine-type "${{ env.dataproc_instance_type }}" \
            --worker-boot-disk-type pd-ssd \
            --worker-boot-disk-size 500 \
            --image-version 2.2-debian12 \
            --properties spark:spark.history.fs.gs.outputstream.type=FLUSHABLE_COMPOSITE \
            --project ${{ env.project }}

          gcloud dataproc jobs submit spark \
            --class=com.aerospike.firefly.bulkloader.SparkBulkLoader \
            --jars="${{ env.bulk_jar_uri }}" \
            --cluster="${{ env.dataproc_name }}" \
            --region="${{ env.region }}" \
            -- -c "${{ env.properties_file_uri }}" \

      - name: Stop dataproc cluster
        if: always()
        run: |
          gcloud dataproc jobs delete -q --region ${{ env.region }} "$(gcloud dataproc jobs list --cluster="${{ env.dataproc_name }}" --region="${{ env.region }}" --format="value(JOB_ID)")"
          gcloud dataproc clusters delete -q --region=${{ env.region }} ${{ env.dataproc_name }}

      - name: Deploy Aerospike Graph Service
        run: |
          # Create Graph machine.
          aerolab client create none --zone=${{ env.zone }} --disk=pd-ssd:40 --instance ${{ env.graph_instance_type }} -n ${{ env.graph_name }}
          
          # Generate graph properties.
          aerolab cluster list -j | jq '.' > ${{ github.workspace }}/clusters.json
          python3 ./scripts/generate_graph_config.py ${{ env.aerospike_name }} ${{ github.workspace }}/graph-config.properties
          python3 ./scripts/generate_graph_start_script.py ${{ env.ags_image }} ${{ env.aerobot-pw }} ${{ github.workspace }}/run-benchmark-graph.sh
          cat ${{ github.workspace }}/run-benchmark-graph.sh
          
          # Put graph properties, ags image, and launch script on the graph machine.
          gcloud compute scp --zone=${{ env.zone }} ${{ github.workspace }}/graph-config.properties aerolab4-${{ env.graph_name }}-1:graph-config.properties
          gcloud compute scp --zone=${{ env.zone }} ${{ github.workspace }}/run-benchmark-graph.sh aerolab4-${{ env.graph_name }}-1:run-benchmark-graph.sh
          
          # Run the graph service.
          gcloud compute ssh --zone=${{ env.zone }} aerolab4-${{ env.graph_name }}-1 -- "sudo bash run-benchmark-graph.sh"

      - name: Run Tinkerbench
        run: |
          # Create client machine.
          aerolab client create none --zone=${{ env.zone }} --disk=pd-ssd:40 --instance ${{ env.client_instance_type }} -n ${{ env.benchmark_client_name }}
          aerolab client list -j | jq '.' > ${{ github.workspace }}/clients.json
          python3 ./scripts/generate_tinkerbench_config.py ${{ env.graph_name }} ${{ github.workspace }}/tinkerbench-config.properties
          gcloud compute scp --zone=${{ env.zone }} ${{ github.workspace }}/scripts/run-benchmark-gcp-tinkerbench.sh aerolab4-${{ env.benchmark_client_name }}-1:run-benchmark-gcp-tinkerbench.sh
          gcloud compute scp --zone=${{ env.zone }} ${{ github.workspace }}/tinkerbench-config.properties aerolab4-${{ env.benchmark_client_name }}-1:tinkerbench-config.properties
          gcloud compute ssh --zone=${{ env.zone }} aerolab4-${{ env.benchmark_client_name }}-1 --command "sudo bash run-benchmark-gcp-tinkerbench.sh"

      - name: Retrieve Tinkerbench Results
        run: |
          tinkerbench_result_dir=$(gcloud compute ssh --zone=${{ env.zone }} aerolab4-${{ env.benchmark_client_name }}-1 --command "pwd")
          gcloud compute scp --zone=${{ env.zone }} aerolab4-${{ env.benchmark_client_name }}-1:${tinkerbench_result_dir}/tinkerbench/benchmark-ci-result-* tinkerbench_output.json

      - name: Publish Benchmark Results
        uses: benchmark-action/github-action-benchmark@4bdcce38c94cec68da58d012ac24b7b1155efe8b # v1.20.7
        with:
          name: Publish Benchmark Results
          tool: 'customSmallerIsBetter'
          output-file-path: tinkerbench_output.json
          auto-push: true
          alert-threshold: '105%'
          comment-on-alert: true
          fail-on-alert: false
          max-items-in-chart: 750
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: docs/

      - name: Stop Tinkerbench machine
        if: always()
        run: |
          yes | aerolab client destroy -n "${{ env.benchmark_client_name }}"

      - name: Stop Graph machine
        if: always()
        run: |
          yes | aerolab client destroy -n "${{ env.graph_name }}"

      - name: Stop Aerospike cluster
        if: always()
        run: |
          yes | aerolab cluster destroy -n "${{ env.aerospike_name }}"
